---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authelia-db
  namespace: authelia
spec:
  instances: 1
  storage:
    storageClass: ceph-block
    size: 1Gi
  walStorage:
    storageClass: ceph-block
    size: 1Gi
  bootstrap:
    initdb:
      database: authelia
      owner: authelia
  backup:
    retentionPolicy: "30d"
    target: prefer-standby
    barmanObjectStore:
      destinationPath: s3://cnpg-authelia/patch/authelia/cnpg
      endpointURL: https://rustfs.internal.stplabs.io
      serverName: authelia-db
      s3Credentials:
        accessKeyId:
          name: authelia-db-backup-s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: authelia-db-backup-s3-creds
          key: ACCESS_SECRET_KEY
      data:
        compression: bzip2
        jobs: 2
      wal:
        compression: bzip2
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
