apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
  namespace: mealie
spec:
  values:
    persistence:
      data:
        size: 5Gi
    cnpg:
      main:
        storage:
          size: 2Gi
