apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
  namespace: mealie
spec:
  values:
    persistence:
      data:
        size: 1Gi
    cnpg:
      main:
        cluster:
          storage:
            size: 1Gi
          walStorage:
            size: 1Gi
