---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dex-db
  namespace: dex
spec:
  instances: 1
  storage:
    storageClass: ceph-block
    size: 1Gi
  walStorage:
    storageClass: ceph-block
    size: 1Gi
  bootstrap:
    initdb:
      database: dex
      owner: dex
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      memory: 256Mi
