apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dex
  namespace: dex
spec:
  interval: 30m
  chart:
    spec:
      chart: dex
      sourceRef:
        kind: HelmRepository
        name: dex
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: dex-secret
      valuesKey: values.yaml
  values:
    replicaCount: 1
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 128Mi
    envVars:
      - name: DEX_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: dex-db-app
            key: password
      - name: DEX_ADMIN_HASH
        valueFrom:
          secretKeyRef:
            name: dex-secret
            key: adminHash
    volumes:
      - name: theme
        configMap:
          name: dex-theme
    volumeMounts:
      - name: theme
        mountPath: /srv/dex/web/themes/dark/styles.css
        subPath: styles.css
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    config:
      storage:
        type: postgres
        config:
          host: dex-db-rw
          port: 5432
          database: dex
          user: dex
          password: $DEX_DB_PASSWORD
          ssl:
            mode: require
      web:
        http: 0.0.0.0:5556
      logger:
        level: info
        format: text
      oauth2:
        skipApprovalScreen: false
      frontend:
        theme: dark
        issuer: STP Labs
      enablePasswordDB: true
      staticPasswords:
        - email: admin@stplabs.io
          username: admin
          userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"
          hashFromEnv: DEX_ADMIN_HASH
