---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 30m
  chart:
    spec:
      chart: rook-ceph-cluster
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: rook-release
        namespace: flux-system
      version: "v1.17.7"
  values:
    toolbox:
      enabled: true
      resources:
    cephClusterSpec:
      cephVersion:
        allowUnsupported: false
        image: quay.io/ceph/ceph:v19.2.3
      continueUpgradeAfterChecksEvenIfNotHealthy: false
      crashCollector:
        disable: false
      dataDirHostPath: /var/lib/rook
      logCollector:
        enabled: true
        maxLogSize: 500M
        periodicity: daily
      network:
        provider: host
      placement:
        all:
          tolerations:
          - effect: NoSchedule
            key: storage-node
            operator: Exists
      priorityClassNames:
        mgr: system-cluster-critical
        mon: system-node-critical
        osd: system-node-critical
      resources:
        cleanup: null
        crashcollector: null
        exporter: null
        logcollector: null
        mgr: null
        mgr-sidecar: null
        mon: null
        osd: null
        prepareosd: null
      security:
        kms:
          connectionDetails: {}
      skipUpgradeChecks: false
      storage:
        config:
          crushRoot: default
          storeType: bluestore
        devices:
        - name: sdb
        useAllDevices: false
        useAllNodes: true
      waitTimeoutForHealthyOSDInMinutes: 10
    cephObjectStores:
    - name: ceph-objectstore
      spec:
        gateway:
          resources: null
      storageClass:
        enabled: false
    cleanupPolicy:
      allowUninstallWithVolumeClaimsPresent: false
      confirmation: ""
      sanitizeDisks:
        dataSource: zero
        iteration: 1
        method: quick
    configOverride: |
      [global]
      mon_allow_pool_delete = true
      bdev_enable_discard = true
      bdev_async_discard = true
      osd_pool_default_size = 3
      osd_pool_default_min_size = 2
    ingress:
      dashboard:
        enabled: false
    removeOSDsIfOutAndSafeToRemove: false

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  name: rook-ceph
  namespace: rook-ceph
spec:
  ingressClassName: nginx
  rules:
  - host: rook-ceph.staging.stplabs.io
    http:
      paths:
      - backend:
          service:
            name: rook-ceph-mgr-dashboard
            port:
              number: 8443
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - rook-ceph.staging.stplabs.io
    secretName: rook-ceph-tls
