---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-base
  namespace: flux-system
spec:
  dependsOn:
    - name: repositories
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base
  prune: false
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-config
  namespace: flux-system
spec:
  dependsOn:
    - name: repositories
    - name: infra-base
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/config
  prune: true
  wait: true
  patches:
    - target:
        kind: IPAddressPool
        group: metallb.io
        name: ip-address-pool
      patch: |
        - op: add
          path: /spec
          value:
            addresses:
            - "10.120.0.200/29"

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-operators
  namespace: flux-system
spec:
  dependsOn:
    - name: repositories
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/operators
  prune: false
  wait: true

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-storage
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-operators
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/storage
  prune: false
  wait: true
  patches:
    - target:
        kind: Ingress
        name: rook-ceph
      patch: |
        - op: replace
          path: /spec/rules/0/host
          value: rook-ceph.stplabs.io
        - op: replace
          path: /spec/tls/0/hosts/0
          value: rook-ceph.stplabs.io

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-monitoring
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-storage
  interval: 1h
  retryInterval: 1m
  timeout: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/monitoring
  prune: true
  wait: true
  patches:
    - target:
        kind: Ingress
        name: grafana
      patch: |
        - op: replace
          path: /spec/rules/0/host
          value: grafana.stplabs.io
        - op: replace
          path: /spec/tls/0/hosts/0
          value: grafana.stplabs.io
    - target:
        kind: HelmRelease
        name: kube-prometheus-stack
      patch: |
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: kube-prometheus-stack
          namespace: monitoring
        spec:
          values:
            prometheus:
              prometheusSpec:
                storageSpec:
                  volumeClaimTemplate:
                    spec:
                      resources:
                        requests:
                          storage: 50Gi
            alertmanager:
              alertmanagerSpec:
                secrets:
                  - alertmanager-slack
                storage:
                  volumeClaimTemplate:
                    spec:
                      resources:
                        requests:
                          storage: 5Gi
              config:
                global:
                  slack_api_url_file: /etc/alertmanager/secrets/alertmanager-slack/slack_api_url
                route:
                  receiver: slack-notifications
                  group_by: ['alertname', 'namespace']
                  group_wait: 30s
                  group_interval: 5m
                  repeat_interval: 12h
                  routes:
                    - receiver: "null"
                      matchers:
                        - alertname = "Watchdog"
                receivers:
                  - name: "null"
                  - name: slack-notifications
                    slack_configs:
                      - channel: '#monitoring-production'
                        send_resolved: true
                        title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}'
                        text: |-
                          {{ range .Alerts }}
                          *Severity:* {{ .Labels.severity }}
                          *Summary:* {{ .Annotations.summary }}
                          *Description:* {{ .Annotations.description }}
                          {{ end }}
    - target:
        kind: HelmRelease
        name: loki
      patch: |
        apiVersion: helm.toolkit.fluxcd.io/v2
        kind: HelmRelease
        metadata:
          name: loki
          namespace: monitoring
        spec:
          values:
            singleBinary:
              resources:
                requests:
                  cpu: "250m"
                  memory: "256Mi"
              persistence:
                size: 100Gi

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infra-secrets
  namespace: flux-system
spec:
  dependsOn:
    - name: infra-monitoring
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./clusters/production/secrets
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
