apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
  namespace: mealie
spec:
  interval: 30m
  chart:
    spec:
      chart: mealie
      sourceRef:
        kind: HelmRepository
        name: trueforge
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: mealie-db-secret
      valuesKey: password
      targetPath: cnpg.main.password
    - kind: Secret
      name: mealie-backup-secret
      valuesKey: accessKey
      targetPath: credentials.rustfs.accessKey
    - kind: Secret
      name: mealie-backup-secret
      valuesKey: secretKey
      targetPath: credentials.rustfs.secretKey
    - kind: Secret
      name: mealie-backup-secret
      valuesKey: encrKey
      targetPath: credentials.rustfs.encrKey
  values:
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
          nginx.ingress.kubernetes.io/ssl-redirect: "true"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-buffering: "off"
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
          nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
        hosts:
          - host: mealie.staging.stplabs.io
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - mealie.staging.stplabs.io
            secretName: mealie-tls
    persistence:
      data:
        enabled: true
        storageClass: ceph-block
    credentials:
      rustfs:
        type: s3
        url: https://rustfs.internal.stplabs.io
        bucket: cnpg-mealie
        path: ""
        region: us-east-1
    cnpg:
      main:
        backups:
          enabled: true
          credentials: rustfs
          retentionPolicy: "30d"
          scheduledBackups:
            - name: daily-backup
              schedule: "0 0 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false

