---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    kubernetes.io/metadata.name: monitoring

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: ">=65.0.0 <70.0.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 12h
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    crds: Skip
    remediation:
      retries: 3
  values:
    grafana:
      enabled: false
    prometheus-node-exporter:
      tolerations:
        - operator: Exists
    prometheus:
      prometheusSpec:
        retention: 30d
        additionalAlertManagerConfigsSecret:
          name: alertmanager-remote
          key: alertmanager-configs.yaml
        remoteWrite:
          - url: https://telemetry.core.stplabs.io/api/v1/write
            name: core-vm
            basicAuth:
              username:
                name: vm-write-creds
                key: username
              password:
                name: vm-write-creds
                key: password
            queueConfig:
              capacity: 10000
              maxShards: 10
              minShards: 1
              maxSamplesPerSend: 2000
              batchSendDeadline: 5s
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: ceph-block
              resources:
                requests:
                  storage: 5Gi
    kubeProxy:
      enabled: false
    kubeControllerManager:
      enabled: false
    kubeScheduler:
      enabled: false
    alertmanager:
      enabled: false
    kubeEtcd:
      service:
        targetPort: 2381
      serviceMonitor:
        scheme: http

