apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  chart:
    spec:
      version: "28.4.5"
  valuesFrom:
    - kind: Secret
      name: home-assistant-db-secret
      valuesKey: password
      targetPath: cnpg.main.password
    - kind: Secret
      name: home-assistant-backup-secret
      valuesKey: accessKey
      targetPath: credentials.rustfs.accessKey
    - kind: Secret
      name: home-assistant-backup-secret
      valuesKey: secretKey
      targetPath: credentials.rustfs.secretKey
    - kind: Secret
      name: home-assistant-backup-secret
      valuesKey: encrKey
      targetPath: credentials.rustfs.encrKey
  values:
    ingress:
      main:
        hosts:
          - host: home-assistant.external.stplabs.io
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - home-assistant.external.stplabs.io
            secretName: home-assistant-tls
    credentials:
      rustfs:
        type: s3
        url: https://rustfs.internal.stplabs.io
        bucket: cnpg-home-assistant
        path: "production"
        region: us-east-1
    cnpg:
      main:
        backups:
          enabled: true
          credentials: rustfs
          retentionPolicy: "30d"
          scheduledBackups:
            - name: daily-backup
              schedule: "0 0 0 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false

