apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../apps
  - ../../../apps/litellm
  - ../../../apps/mealie-ai-config
  - ../../../apps/mealie-gkeep-sync
patches:
  - path: mealie.yaml
    target:
      kind: HelmRelease
      name: mealie
  - path: home-assistant.yaml
    target:
      kind: HelmRelease
      name: home-assistant
  - path: mealie-ai-config.yaml
    target:
      kind: Job
      name: mealie-ai-config
  - path: mealie-gkeep-sync.yaml
    target:
      kind: HelmRelease
      name: mealie-gkeep-sync
