---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: dex
spec:
  interval: 30m
  chart:
    spec:
      chart: oauth2-proxy
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
      interval: 12h
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    replicaCount: 1
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 64Mi
    config:
      existingSecret: oauth2-proxy-secret
      configFile: ""
    extraArgs:
      provider: oidc
      oidc-issuer-url: https://dex.staging.stplabs.io
      redirect-url: https://auth.staging.stplabs.io/oauth2/callback
      scope: openid profile email groups
      email-domain: "*"
      cookie-domain: .staging.stplabs.io
      cookie-secure: "true"
      whitelist-domain: .staging.stplabs.io
      reverse-proxy: "true"
      set-xauthrequest: "true"
      pass-access-token: "true"
      upstream: static://200
      http-address: 0.0.0.0:4180
    ingress:
      enabled: true
      className: nginx
      path: /
      pathType: Prefix
      annotations:
        cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
