apiVersion: ENC[AES256_GCM,data:Etk=,iv:AzN5m0vgx6ZDcPuJ+6h12TlpEkP5A1GjGpO992ZXc1k=,tag:qLgGEA8BRNrPeW3sZPw/wQ==,type:str]
kind: ENC[AES256_GCM,data:812gsa+N,iv:Zk2fq6E48wQa7LjSDAHrEAnI24ijE0bwRSTKNhIv9Iw=,tag:l105TMdEDP5X0Guiu3hCNw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BH+YJtG5UFbSQkDWPDmr5QtMyQ==,iv:5B+xe06h46lCYy5DjHQk8d788zEcySdPmZQgqAqdUqM=,tag:KcNvrgc1QpKhZR8ifAoZww==,type:str]
    namespace: ENC[AES256_GCM,data:lGjy5FcelJ2r2Q==,iv:DESj9SxfyRFmhb/SwRadgCcYhK7pijpzBkwz/ZKUXtg=,tag:4LwfLQOWdBFMYHqTWS8Cpg==,type:str]
type: ENC[AES256_GCM,data:uQEBkZbn,iv:5a0czMOqRXJ3CfWekiGXVorUs/cOpbFd9F2kd07rbdk=,tag:mdLkzw0zoeae2KOOzWRGOA==,type:str]
stringData:
    alertmanager-configs.yaml: ENC[AES256_GCM,data:yMpaLIOzoPTmm5+Fz36ZX6EIkGvdn66Ds16T2sXjyIQMF/0C0RUw9eowSUzXu1CPQWaaWyYNY9ZAeVZH/1Ats/mh158McUFIBAap5ls2ot3+BWvCGRznwQ1YD/7B11CcBbi/m5CrW2vnSseAiWJmjCzhqCW7J8ocJhNVgU0mmbnJka3QV5HHsPce3nup8DQTjCEpZFl8DHQF9K4bNb6x+3J+RSOmVtdU5o3fO0wV+D2q2UND8eJEFg92ykjMzLhl02KrxEQdVG6tXfrclCjlHWQ1Nw7sixYdETEW40M1OgeiIu/GajnsPGCKFG0R,iv:9rmXktPwYF/zpES0ugr7M8eggUdvL1udweLiPoCt7Fw=,tag:1bNugd4MBdbY3bElazad0w==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MHBKcXI5YWM5UjRiQ1o0
            M3NSQTFtZDhlUDUzd29oY3htZkZzS1NWQ1Y0CmQ1NDk2bVBTN2NhY1NrSkZxYitD
            NlBiSUE4cHIxbmYvTWZyYXFCL01IbGsKLS0tIEs5U2NSQ0JWRE9ETlVWVWk4YS9M
            dGV5a3JMWnJEekFkbW9QV2JuUWZSalUKuGIyCqNluIagJRphBGCr4vZ1y3eW8inN
            V6ZO5xCbqmFyleeZhm/RgXLXFnRlwxoh+1mkZJhn9eVy7DlMr65wGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-15T21:15:01Z"
    mac: ENC[AES256_GCM,data:Wg+YnPjm7Yhcub+Caur3OvCpgNON2TnF+4Q+MCT5HxhjLzC7S+ywSfKlihtClEHZOaObld6RFkZ8gNRBOFWesQR+VkIB9MsDacBn9/K8OwxVEm3/BzHtQkUafoCMfE4kJnEV+iL57PPrXerYt1WAqqIj8ajyv2vrL9cIAq2yqq4=,iv:3HPPL7aTbjV31oxU/zki/EVZHdrph5ugcPlXohLYB88=,tag:flTS1LKeTU8dJwaRGAzdsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
