apiVersion: ENC[AES256_GCM,data:puo=,iv:sqmlceREJUqWLSbqUyZKqZ6k2U0qRN9oTXWIGeAl7dA=,tag:q8fENTl4qjf23o9dsOEiGQ==,type:str]
kind: ENC[AES256_GCM,data:uNB0nBJg,iv:pOvbS2pK+CctQf+tFfSYqAttUcf9ct4bsZ+8VGbhOlM=,tag:X0X/1r0WnAEYDvHIdLVCsA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:A8PKxco22Eto/pE+Pno5ecjL,iv:uulJtHoOBRY3AKbtyxvV78PYpUmcryp7x9ON1IFcetg=,tag:E52zgWi3u//pgeVrzq/i3Q==,type:str]
    namespace: ENC[AES256_GCM,data:lJatVdGKH0+wzg==,iv:YbT+8vQETsj2hCB1R2HIqRD9BtuEoDGl/DElDf1apLM=,tag:SvzenIegOd7MXAl97G3Y1A==,type:str]
type: ENC[AES256_GCM,data:ghCWT1X/,iv:m/7wyzOxBKKlOA8QTLzKWSH4/7L0cjrvtjRsKjAAeH4=,tag:d84sPsTSTyG2wy7Y/A1LQw==,type:str]
stringData:
    slack_api_url: ENC[AES256_GCM,data:R+rmJgWdSuBMyChM+gs8Kv45kTQJSHBbHy7DjvETp3KgJ93Lq2jTWxxM5Xqg4gTCwDmPeqICDoeOHw9klntofgVdVQOAtb6vyrqv6OKxBqBc,iv:NO5ZSf/+CESbKMhQ6hl4nBvI5VzqwzcUJaGlGYgHIP4=,tag:EG2xHPHQbAVM1VQyD9qkBA==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQUdObHJSREtlczdZQ3M3
            ZnVGL1g1dTdGb2ZHQmNlUkV5WE9aelpJRTI0CnRJKytIV1RVUzhkK2JmVzZQS3Ba
            VnBjSlpST0ExazJ5aGVlYTI4ZmVjREkKLS0tIEltbTdMK3ZOZ3Ftem90bEp5Z0VC
            bmk1SHpaR1k2ZysvOVB1bDZ0YngvQVEKdIFyK/I+YF91sY+Mn99PNOQUeQEu4ClM
            E12LGcthep9WfVKPfjGCEn26fStsbXHltf7LXLiOwHzD/DFHHJJJDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T03:20:42Z"
    mac: ENC[AES256_GCM,data:kDvcZIUk+deoztVhCk7U2JE9mY4S7kRJCYSuvUW2dzdqLsLCDiv6w2DMjFQtN6wtJPXOcKp3X6weLLov1Hk68xA9cUZfA7Azp/ZH3Zf2frEhMXqsZFtnwuv6+PhC+uemaRSU8csq4alexOi9ZUmc/bdj/hL4GD41G5CV72GHmRI=,iv:N+X3uXgzfkTopwUgRvGdEySl0J2zbKgG8XBy0UY5Flg=,tag:KIG0BgCMVhmuWELb/nu3+w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
