apiVersion: ENC[AES256_GCM,data:Etk=,iv:AzN5m0vgx6ZDcPuJ+6h12TlpEkP5A1GjGpO992ZXc1k=,tag:qLgGEA8BRNrPeW3sZPw/wQ==,type:str]
kind: ENC[AES256_GCM,data:812gsa+N,iv:Zk2fq6E48wQa7LjSDAHrEAnI24ijE0bwRSTKNhIv9Iw=,tag:l105TMdEDP5X0Guiu3hCNw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BH+YJtG5UFbSQkDWPDmr5QtMyQ==,iv:5B+xe06h46lCYy5DjHQk8d788zEcySdPmZQgqAqdUqM=,tag:KcNvrgc1QpKhZR8ifAoZww==,type:str]
    namespace: ENC[AES256_GCM,data:lGjy5FcelJ2r2Q==,iv:DESj9SxfyRFmhb/SwRadgCcYhK7pijpzBkwz/ZKUXtg=,tag:4LwfLQOWdBFMYHqTWS8Cpg==,type:str]
type: ENC[AES256_GCM,data:uQEBkZbn,iv:5a0czMOqRXJ3CfWekiGXVorUs/cOpbFd9F2kd07rbdk=,tag:mdLkzw0zoeae2KOOzWRGOA==,type:str]
stringData:
    alertmanager-configs.yaml: ENC[AES256_GCM,data:bpwpkb7R1PlWj+Q7+KI3ShGUoB4Y2dJjEUwJeD4EPPkJzMVyy7J9OVw35umQyUc8DwCFQgQ1yD7J83lLFQFhRHc3B7H/dBLWuP2hMDwz5KRf0ZbRZOe4Tt46HDrIJ4MTSzYE18KRXa3uSUErHX+aaDfIZwQm9x4lUcNbwqyMZAktoqhSZdE13+L6xlNwFaEmZBumCLyURZ8CskvhjNDXtE4sUKFKInEaZ24ZJSdIdqE/i3TbCMlqIX7S+TII8MgONEzahFgu9L3PoILyBmXJmY1K/fwk4NSuXq+2xkxJ1gVSiQxN5KJtnzaH+A==,iv:j0850VKoDPo/Hb6jlAQJM4FDyK/NH0FqlPHGavKXnbg=,tag:48eAxU55hEB6gWxIL3Q1VA==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MHBKcXI5YWM5UjRiQ1o0
            M3NSQTFtZDhlUDUzd29oY3htZkZzS1NWQ1Y0CmQ1NDk2bVBTN2NhY1NrSkZxYitD
            NlBiSUE4cHIxbmYvTWZyYXFCL01IbGsKLS0tIEs5U2NSQ0JWRE9ETlVWVWk4YS9M
            dGV5a3JMWnJEekFkbW9QV2JuUWZSalUKuGIyCqNluIagJRphBGCr4vZ1y3eW8inN
            V6ZO5xCbqmFyleeZhm/RgXLXFnRlwxoh+1mkZJhn9eVy7DlMr65wGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T03:22:37Z"
    mac: ENC[AES256_GCM,data:lqDIdEuWt2O38XtvEzjQY5ueqwxeFyB2kECcrvGGKtpQ3Q5MQthP70awaHsbakOB7pQnnoA3xJgXiRE3t3aDgWg/CQ5Jw0ieAZ+HMGuYLkS1DyLptSFg8XJp0B7fNzde/VJLiPOR8uIz+wzeXCarHZ7FvoG4qkee0MPxU629Ngk=,iv:mBjlSqt2eJRVG+PEnWWctCaWKfIk7eDHj394LstxwkA=,tag:8JDSbv4m8nJUHJZbVqNI/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
