apiVersion: ENC[AES256_GCM,data:VzM=,iv:7khZEvLE08TmbJOWB4RkfTiGZ1VgKKUqqjvfSeVG53o=,tag:2NAHVEZHsM0pDoQ0WRAlQA==,type:str]
kind: ENC[AES256_GCM,data:uzPnJEJ2,iv:m2W6tc+Al8D3pYnFRXB8Tg00gBs4vWhlJCpOGo8bFgY=,tag:02O9WitAeLEHCxJIrxim7A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:NwVLfTyUZGlUbjLeJiQtNt0/lZpeSKtbwVVt,iv:WXr2/RWPO05hZx4eyfZfumW+VrNSwXcDosvkQwd/klU=,tag:58NqLndEtsrHZrraexHSfg==,type:str]
    namespace: ENC[AES256_GCM,data:v0KMg7SDhRU=,iv:5SBDCkbUS13tDMlTHuJKre6TpKFypdzeTNYuK6TQFkU=,tag:3udjL90xTxYmX1vNRJn7mQ==,type:str]
type: ENC[AES256_GCM,data:S/i81KBr,iv:321Sz5t4fpPgrd+VHszZYD7Pg0/PuwE48OiXLaFinxQ=,tag:hSlAfmRtyqNA2CXNtD5KHw==,type:str]
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:rqXFFvTD7uJCg5Xvn8J1fUEujws=,iv:LtAQxS7gHtJNZrb/hYgXiRnAqTx6wwbJ5aUcLQv5R68=,tag:ioDa9n83UGVSzDqL34Bq6g==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:OyKanNufa0w80Wm9IWEKyjlkWDFQKDGgDJ7v1jVGOIGGLIwXIWT6IA==,iv:MnasjBH/TElpd/ukjvB+Wtxe5/iGEVNWZUwJPg4q2xM=,tag:WGoSj3wHFO7YxgWwXuxlFw==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OHA1MHZXUUtSVnQ3K3FC
            QkY0eWMzYThiNDIxb3dVU3hFSTRUa0VPVmk0Cno3YUJuS3dSajdsbU1xTFRnalFL
            bHJac25Jb2NqQks2eFRlb3JudXMwSE0KLS0tIGxFLzBSTUFkRDNzMXNGQWQvR3dU
            Sk81RXE5UWxjNnUwdjhmZ2RTc2NwM3cK8cxt2RtFa1Gj88Rnl4XP3HymwbtXkymO
            Nya4YAmIQ+E7uBV+6knPWQaiy99rxSKpToqp7+w8TuNy2nq65lypzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-22T19:00:40Z"
    mac: ENC[AES256_GCM,data:1/pr+85agJF5NIFpZ1h1FdBiuUPXQ3/IZEiKcYFHBqUQ/zUQIGNtdMySHYq8Tv5WBoXQuKplNuPpWFl5m9TCRAs8v6n1vpcCEpmRAAP+blMK5kuc5MJGES1+bK6u5qNSU5WLkSPnxZ70HzbPH/BrjHwWbNZsv1OL2ARIWH1/fEg=,iv:C0fDOA87wECWt71+Oci7TCscSo6LpoahCIVF5J3YDu4=,tag:cVW73Lg/JGpUlpBn2ZE/Zw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
