apiVersion: ENC[AES256_GCM,data:DWY=,iv:ag95AWFFU/axrrY2wsEt4HDciwj2ChxXpdDe4/Kh5CA=,tag:TIIe5eINpNoojtRYOuVwIg==,type:str]
kind: ENC[AES256_GCM,data:oke1WgxI,iv:M6uT3lf8xFGkKhNA7Iay2HELNQ6xR03Xa8ZwmGKeX98=,tag:HqAI15ZXRnykzrrfVlNBdQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vdKag8awyRyRRfsZjAMFoJmnNYI=,iv:FKW4yo3MMXH16Q7HM5yhGj0WCfehA6PZ6ZEBaGLIFA8=,tag:kJRf9jKSciPQLh9kIGd46w==,type:str]
    namespace: ENC[AES256_GCM,data:oIEhIPAUr5E=,iv:FbO0rqT3q+C9R/D5ijwnQSpNH9yBd5xBYWBSJ6UfdW8=,tag:+lK6x3CvALzi3jtHq9KEzg==,type:str]
type: ENC[AES256_GCM,data:++FFQ6ph,iv:fWCAuogIUBQpE6qkhVGbYrepy/Ads1cITlwtZHwSKNs=,tag:gPvrsaKMM6wQzdq97GJwOg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:XWcmQxJrTur9xv3sfRrYFglv7Q==,iv:oWkUxISOzeKJeXJtw+XIdQDRUJgNmf6onJtlb/RbTn8=,tag:udOrdF4nV1+GN5MFx0g2Eg==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UnVNMmNSYTNLT1FPRG1I
            MFNpMDFvNFQ1WmFtdWdYUHVicnpQWlFQSTJnCmNHMWVXd3JsaldSdkNzUXBsUFZD
            SERQc3ZIeXFxMTdvb0ozODFzNlhabDgKLS0tIDN3QzlJWFdBeE1jaDZxd1FBbjls
            bjBNSjk3bjhsblZDUUJWZ3dqOVlwbGMKb9Dv37gUZV3takNN7UKsKIKPxlDhVzJw
            IrDSJwcMoYlpDCJcU7+zXWR0dbh17AXUAOFhdXP86M88aGXUhKLq2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T14:59:40Z"
    mac: ENC[AES256_GCM,data:wV0EY7XxXIJhvAsXAGSlA2GDoW1KI/8UrtR8uYs9x9ClFofJ7D+uN8lmpPFM2e+XEaMDUlVfwayEuBirnn47aEJgqCMqQm+HYBKSfAvfRmn8tqjvlld6MPyRWogDRIJ7bV4Xb3OzBf5BX289NvDbxnUz/LVfdRfq6bXLj+H7lNw=,iv:kIrwP1BPf9Jd8fogmb39gBltCSB25mhOiFmT9XI5ai4=,tag:8xEfExSHWhCVMyoAgOubRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
