apiVersion: ENC[AES256_GCM,data:GzI=,iv:Bc7+XvbX497ZTIfBkrQUhDuVugOLy8iiFIhf0VhlpYg=,tag:T25Q9SV9CIcR2+S5qsi8oA==,type:str]
kind: ENC[AES256_GCM,data:ezXcpDIA,iv:Iaj8496hEVVhSiKSZRywoW6q8n51Nt1LPya+ZNHInwY=,tag:MaB+frwXh+rlrS4obvwQlg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PL/OIoEshj+q0uWuTN0StoKW8ObK,iv:mz0xkeVNiHAHxUrbtw9bz2OVRq8oga1p1fyoeKNKCyo=,tag:1yf4lpoj9eYw9Lmo6e+Lrw==,type:str]
    namespace: ENC[AES256_GCM,data:X92+b7cD1Qk=,iv:6Mzg+sXaL3NMIm1xMwLWopEM5r85DwCaVMY+AFel53Q=,tag:y3uTOW34Llg+ldJC/IVgiw==,type:str]
type: ENC[AES256_GCM,data:D9Ykjn9/,iv:hGJDheR9eaaG9spRx3uWCLdHQ57HSJTbIxKpKoO9kMQ=,tag:iDLX76bdqLq2om0MeVQKnA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:UV3pH+6BOh8JaUPQpQ3rGn5W/TYx1EjmeXDhZmzqVp8=,iv:NDbpVPCWRUJqJimUvocNgtXoXcDO/PPqyEarE4RJUlk=,tag:xf7BA+JCmrdjGzX1kp+IZA==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSGVsUWdQUzdTUk5tWEps
            cjY4WVFWOU9ZcG4wemtUaGhhVU1nN2U2UW00CjVycVV6aWtWV3pmUWQ3eUhlMUR5
            YmRKb1ByUTdHVXpMOWJndHVydm93TUkKLS0tIEdSSW9waFdzY09IdVVEMldnRUdP
            WnpHMW9FbnJTVEw5NHh0SHo1MHpvblkKS386MLAHg4i69ofMsXq8rPp4oM2Y2WNL
            SdCB5dCPmNGAvK6JNP2TOe4eN7UlgPLtJXKYDx7kNraW4jRaMASWbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T14:17:54Z"
    mac: ENC[AES256_GCM,data:bEQHy5iOF233fbNSbhsmmqmIsX7SUpO8SM+LWQfUsiTKSSJco/W4p/rPD1vKl/+2d695sA/kgEcNfARs09CeFzUM48Eb7mH+LqTHWtu8DBfQxZjjAuNm2xps0CQqbTW+WTebF+956URfQb9omHn7mcSfWfMyBmIOVxzteXj9Lg8=,iv:fdaz8ZYUNUOZwJgCXGOmQ3YhPDGxW4Lof6rsEc14BeM=,tag:dIcWK2MyMZ0+Qp5XaU4xlA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
