apiVersion: ENC[AES256_GCM,data:BhQ=,iv:VeV/wSqdo8ueX4u1FqVRsdMycnOVjSM+sw/ehaVOOCc=,tag:JWwNrRpx4X4qKNvd0eJnhw==,type:str]
kind: ENC[AES256_GCM,data:kxuz6fyU,iv:0QUnCZk9TOg6uiYUP+WoLAIRBAnQhhQ1RMZRdXVLKXQ=,tag:Gf+ChYIG0V3ZSMg9yymKWg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9Wm3qpcwIEA7fA==,iv:yg1zuvxrKvT2OZ19C7ruQkhr0g8vgUyPcCmIJDfmexM=,tag:Z0wk+u9kzxyeTfqIToyC/A==,type:str]
    namespace: ENC[AES256_GCM,data:GUax,iv:Evz1HIoDBwCYOctbtmT+OmNI1olwjDMjvzzb0Wr6TvY=,tag:Gdvq/5h9U8mAfsPVNg2e3Q==,type:str]
type: ENC[AES256_GCM,data:5Cb6qQFG,iv:0rSNt/2cnfvq9xSEmj+p9ApCrfvqUO7CwDsZRYp1e8Q=,tag:GIVETOGCrHuu5G2zznEYLQ==,type:str]
stringData:
    adminHash: ENC[AES256_GCM,data:cjBTuOYeaOvdxLxfla1soboGgBb2UHQGIJRMuZ1aRCk4Iycoehdn2v/ZirSh1xSq1yau7FV5F7BduNV+,iv:E2Yq6qi/abf3mzprSMF6fCk9IZGGkThZOc9vUjQpGww=,tag:2DFxKugEn6mMiokUhpLIOw==,type:str]
    values.yaml: ENC[AES256_GCM,data:mgCy+n+fEznipGc1jq6zV462CQsLi5gQIFNI/tFvVJNIFzvMJ1CWJ8I+pi4y4ZcDLkIpQUQib0vptvNGwmI5nwwGmQr7xtzKcQMZ8a//jJzud/uF0iKthuV2YYlfLoRyRv9HsXZ3U3aG5T0MnyzGKnRUWGSuZyFMQkN9r0bkUmmOmxOTy5AEDL4pwATgzo3N5CWA77TxcYPtLpYQWU4sPWSIU+0aHcerybO3zetYopVbajFjG1UoCDcja29+VQVlwMFfKouwJZQN0aTqWj7pnWE9xjTi++Ul9yeoRsLDWD2lv7xAew==,iv:vpETIhiRIlmFtzYbZ+lxI+4tNSqnI0eBLhGgUpS4Ayg=,tag:jgRMDg+YFcgNuWm/4hxf+Q==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNclNhdUZzZ2ZpemRYSFNE
            UGdpaklmbU5YbHUyekd3dExKZkNjUEtlUWl3ClU2Y0FySUxSZzdtVGRNV1BWVDVt
            bllaeXVpajdjWEVCMGgwZkVjQzRPUzQKLS0tIDJzWllEa1oxcmZFSmRnWmIySU5Q
            OVRBcmZPWUQxb203bjZxT1pTaldsUFEKd2viRGdv8A5gLXHaJEyX2x4QGLZ3n2Ev
            aoVMzitrFaJ5WIYRmktmqQPOBJZ4M2W18sjFVQ2akRgr9rUCzz1ldg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T20:03:35Z"
    mac: ENC[AES256_GCM,data:518p9WowR+mBE8xZ8ed1A88/plheR3JB+mOTi064XtfjWFoC1uLbA7xA2T22lvqoy5wYDpwit+RlVGNq3rLSMCxcgWIUEAGgXVVBzkIeJngK6RhwkTddgNdhnVNG4bVaOjdPxmoCoJPOQ98eDwgatBAPTyot4geDaN5Po9r6bf0=,iv:vuOVD6WvvG4sG9rICd/POdXB+89g73fRQaY/CvUFUp4=,tag:J0BgTsZDfC+m+8e86dWn6w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
