apiVersion: ENC[AES256_GCM,data:G9U=,iv:S6jm/1HEpwTS6cFX0QEgesDTNSalzRNAoqCo52wMOXE=,tag:HtHCwHHBzUTB7SCCRZ+1Ng==,type:str]
kind: ENC[AES256_GCM,data:CLoGmE+2,iv:+r+0gqLsEOybBjixsjmwSP1YDxoM5kS8HJDRzR+yij4=,tag:cl5vNY8rCVmHtYOdlCk3NQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:CVSBqBZNgnol1g==,iv:X4K1Vz9czdd57Y6gQV0916ZES3L/PuTkarho/+94vSQ=,tag:6rVuSjhFHlnZhuO7gZXSxQ==,type:str]
    namespace: ENC[AES256_GCM,data:zDzu,iv:LqhIsOf3B08tYJRAdLtIWvFn7Etz/a948mcinUsh5BU=,tag:uoc9QdoWojfKNpfooc+Fhw==,type:str]
type: ENC[AES256_GCM,data:dRqmikOS,iv:/3lUDMj/WCX5uRFayKy6ONfpfzKaUgJu6d+7OBUi7uo=,tag:sBS9e1UjlFc1BrQ6W7ZLXw==,type:str]
stringData:
    adminHash: ENC[AES256_GCM,data:eveOoQtDxX64bSlwDfCPvbz+EShk6z24gXCKzIHFln37/TzzEGTUtUlVvERnjJj5IngRNc2okUafdyxE,iv://Ew5nBToQIYMBS2pKNoyffGnGB+KYUOatBL+biF6Ic=,tag:ikzvRKRTWhEaj0qQO2x+Ng==,type:str]
    values.yaml: ENC[AES256_GCM,data:K9l72g5V/Hb4gSuFnJndv+fI6RqBZODJp0mwW9vknJ9MZX0FrggyyBpiMj+Sig0WzQe2rQ9xjgZ/Qav+Syena8r4STrzV2JVfahbMn9laIEEQ49GcrTZ94xwyGUlNWBzd1lc102KtvqnlzaA3wffsn3SLD5SIDVe+F2BCwyLcTLyiM++CIla2LLl0z6hD5H5ZGQggbOUuo9uCUQXGy4/GLVVY/Zh+ZqjmcO+PgizYVeRw7kN/kKn4SE/SsffFxH8rvEF/ahDaiRbAZlOyNq7R0AIQimXtgkm/3mWl/tLHYomcYpPsQ==,iv:KfQOLUjkzWhtdv/Fg0Q9uB14Jwy8WuJhmEHzBbd12Yg=,tag:RuaJZQHTjJi87EDc+zdq4Q==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMjNRMHlpMHlzemVnbFNC
            UWtKU0ZpVmdtWmtPVG03SjZ4blAxZk0yZWlrCmFZOFJFQTNaUk9sb0U0dmlIQnN5
            VVhsSzFxN01lYnpOQ3Y4cnZDMVAwUDgKLS0tIDRsVXI2VC8rUEpWSmY2OW55ekZr
            dDZUUTJEemw0VENremtwMlNTcndCQ2MKsgKVl13c2ysGuwPrtVJk51srqaqcX0sg
            q2MaF5GsUiSSKUOEx7X4XHOzDzW9dVIM11bGwXMv5h0EXl74rVFJsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-01T22:27:13Z"
    mac: ENC[AES256_GCM,data:Zo5enUAId+69tdWNJTWuof7YeYdKC/+9RROoZHOvc/GO37THNMuWV+ICa8+7c2+WKwBUHi3VTWQGMIN7W7GdmPsG4kvTdpyTjOwRbakS2oEb6Tv/NC7gUc4qAzPV64kS3/iY7KTS7LUo95BENugRyZ3QSd2V5GRYbQyhUmK3Kns=,iv:M8ZIVBUGYmpai7GUX2VJeKRynAjFd4GoWxwASt4orXo=,tag:sOQ8+ErjqzZi113u452XhA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
