apiVersion: ENC[AES256_GCM,data:WaY=,iv:OtSGtF5vI5RH5gGqZBmHKDozLl9kwyA1Ch4M5WL+e7U=,tag:mhTfAUIeF3tu96IxdzSQXg==,type:str]
kind: ENC[AES256_GCM,data:aIr2kdCb,iv:ozDR4lBX9tVOPaXaXlT/HMC1RCISHFokrJfWspjctxc=,tag:fvbpX8Z2NZLIBbF9HoV9RA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:adBmLVE3xmksLNv3fW9mkr5PAg==,iv:6yDBXEOSKDr0pGHInRFp07kz9ugCrWk8Z2OnTzlMrgs=,tag:rOzFyzqMTVXEgWUtUuITSA==,type:str]
    namespace: ENC[AES256_GCM,data:swEB8gh5jLxC+g==,iv:j0xI6fF2XGi9RLMyVW71eCEHckX4d+os/yNl7k7JjSc=,tag:BWuBR0WQ1Pl7KBwAzlCmsg==,type:str]
type: ENC[AES256_GCM,data:Xgx1ZZd8,iv:it8syyVdm4Fy5H+HpG1tgi9E4Ny89uRp1tzh1lJkiLs=,tag:KKohs3RtMbZ5/65AQZ9q6w==,type:str]
stringData:
    clientSecret: ENC[AES256_GCM,data:5bQO3zRgXxxuv5G6vACmf2CtUMId3pvqkp7osMPyjpVGduAXIS1+dfmJgWMMkJdN,iv:GKjhU+mu5E6Y4HMBiu8tmYDeSMlNQ0Vle4I7aSsqjc4=,tag:0g6IRMsiTu6tgoCbigsGdw==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3KzVlU0daZ2tucEpKbUVL
            enlSSWpkbk90ZVJSNmdSMnh3S01nb1p3cmtFCnlkL1JQU1A3UjNvUm4xVzczVEVO
            OTAxR1JTL0IyVVFOUm1UN0VDZlJGQ2cKLS0tIGYzUlVRbkM5YzFOYjMybnl1NVds
            dHFGd2FYa3NlSyttcytPaVFwRks5em8K3flqSa3LKVpqeWVzotLL7boHK1JpV27y
            wws2+RzQgo7b2nBN040JfX/ZRUKAd9I3/BduQhCPJkpwh76f/AhvBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-16T22:10:40Z"
    mac: ENC[AES256_GCM,data:i38PHUIukZf/Z9GDLJmcnyF5IqN4I4J5RkHjt9ocqZ2JXgMNJB57dmJg4R4G1z4uur4krfPjsrvQOXlNqTDFMXP2sJyXbIw1tHNLzraWcKW3RPSBK2Ohe3E2acanHOuE+ZQ5Rc7ma+g9u1zQ2VkBpZVcxq3XGxOdE4OZO8ggec4=,iv:LP25eGcLg6qphFTjZhrv8j8xERXYu6jh7PgB1OSyf+I=,tag:l7/fDhVp8Ymg17vcF3n9MQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
