apiVersion: ENC[AES256_GCM,data:zzc=,iv:chErMqcgWj4T0lHPmCR9H3aWf5OhWK7Ps9BxLQEk1qQ=,tag:0SiUIVs2RYkIHemUZRl37Q==,type:str]
kind: ENC[AES256_GCM,data:SgFQR+Hz,iv:L7eVJy5TUxhw4pT2jmHLxp/JllkYdab95pKpJAZtnzQ=,tag:kYI1OOWUVQwFiV9A4+CRlg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:a+YCfzUcmVMqw+65KMMxet3tZNygRMO0S6uN9A==,iv:pBvPvSt4y2FXQs0bNKGAatuxPp5AzXdzPY1ZwbmdW2o=,tag:l13CiVp0PkD1DSi+PFmAXQ==,type:str]
    namespace: ENC[AES256_GCM,data:Quqsk5obdpDoK8MZxg4=,iv:zztMIi0JbtzxpFwvLuZB0+VX5Mozab982/Tblyb9PsE=,tag:kVQgq7nBiLAeFF0UlZGVcw==,type:str]
type: ENC[AES256_GCM,data:QMXi65F3,iv:+TX+vtaqxxTL4hfX4drbhBQsmUDPLsSSBjdoUJL6Mek=,tag:92Y0Xk1OBF12vEL7cif/aw==,type:str]
stringData:
    accessKey: ENC[AES256_GCM,data:fxkic4q+yJDHxp4fy65avAtU0Vg=,iv:MFmygDK83DA5Cd1Ww77ionxRpjbNGz84BT55HVqxhG0=,tag:4feSjJb9oez0N0stxLzt1g==,type:str]
    secretKey: ENC[AES256_GCM,data:lQgP2MHkuN5flSWi0Wck6dCef/5vRrIzXwLfm4mMlUeS2584oBKDXA==,iv:R0FWgRCxl1YZLh7t6/+RnlI9XICjRq1i9bphlwaxVq0=,tag:mATHGyKQoHnyLo9Oa092Dw==,type:str]
    encrKey: ENC[AES256_GCM,data:o73B6jI32hNJuoX5WwMQAgZYYRlOzMtC4mSR3BTei67e7py4WFhLgPavnmo=,iv:MK+LraVklnbGGIvC56po18gZ8KUYLOp2qMS/1h49Rcc=,tag:54j0MU+k8O1lRrjK6GRU/A==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bmtWVWlGb09vTyt6ZjYy
            TmZLa284RVZCNEhyS3NvZ21EWU5LKy9QMXdNClVXMWJXZkE0ejhXWkM0NTE3YnRU
            NUpDVW5lWWREZFJnMWJTTVFqV0RGOVEKLS0tIGdWejR4OU4rOElTT2hWd0M2OGRT
            MkplWE42Y0R4dGVVek8rZnpLUXdYODAKcEKsqRdXq3YEQgVe2CrrnERbHgrZbEkf
            r+Mvorl9R7y98Tw2Jac4+3II0wO4CbCXr/86Pq/Z3XIQ4pj3YwYCkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T21:05:54Z"
    mac: ENC[AES256_GCM,data:KWEYdWBJQPA+ypQatbtxlALKjcZZO0HvlzpTlFfN55F8BfSDPQP8oQ8995oTk9Z9HvET6elvykT7nfIgdFMkpqHZpI991wCUChD2gb7UL+B6CPFwgcIH1EMEKv+SNshdCx04sHgMoK0wkDG8RoKnuCjZSwoz0Ri94J9+T9s4Zqs=,iv:nEEMuWpLv5Mdyvvk1r2NLrTh5l3voibBtdVaK/dyJqY=,tag:NID1tfb2fFET5Wb3970VIQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
