apiVersion: ENC[AES256_GCM,data:6ik=,iv:/rdd+Xyl4KNoPdwrR2vCjDkU/HnMINl2CISFhXixwxI=,tag:VJY0pDxFT87jEoz2IesQvg==,type:str]
kind: ENC[AES256_GCM,data:HGJESbkY,iv:K54WWHl405aqP11tkGzmdE0/QglIvFtnlMKg71hk7TI=,tag:hCtTxNTjnvB8CzWD1iMqdw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vjcf+3xZ17W8xb0k6QgD+uYnVg6iyczI,iv:XaJed9w0zZl0/55KwYYOCBlyxXy1nxK2OuOxBcDu3Lk=,tag:X6z4aArfp5Ws8XP8wpDrnQ==,type:str]
    namespace: ENC[AES256_GCM,data:wuYIOhsrIaxaK70LgYE=,iv:BoegM/Od0Q0af63dMaPA5Z7KG4ARIHJbUeOjascln9o=,tag:uLuijthPwIknpynTALyBhQ==,type:str]
type: ENC[AES256_GCM,data:77H0nsj8,iv:SEUh3fplXGCbFpnAKfY5P2KOPq51prIGUk1QD4pSqv4=,tag:Mw2nryy2CAuAQ9deOn6U5w==,type:str]
stringData:
    password: ENC[AES256_GCM,data:68sW2WdFlRlmcFdjnH00KLNnvnXYE96r,iv:VmWA++zsk8Pozvt5dIzCZAaYFQiVQfaNNF5Ifwvwecg=,tag:p29EC9OA3oBXQVkxPyopoA==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQjB6b1IvM1BVZUM5RzRF
            TjM1dms4akZ0WWhkaTRYQmNtMlJrWW9WaUh3CnQxbkcxRUlkUmxLTVUxRlFkNHlx
            allIWHJDb3JUNzVsUUxMbWFraTlObmsKLS0tIFFsLzA4cEhUVDJ6eVpxNWJVWDhh
            NG9lMGdmVC9SVE95YjBXVXhTdkRxY1EKoxpreopv0CawdTK5dhuNZH9d+Jl6K4zM
            pAIgJt/4W823fJCsDOvhjFv6lqIBkiR0t/WK3ABR6MS+rCkpeyUMNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T02:28:16Z"
    mac: ENC[AES256_GCM,data:2cmZVXd6pzgczYmDPot/loa36dvBeBMJzXrklpb84RCzJ58tF1P++bpKJNNdEvyexWUd/9ipQ0PcB3nDEk3I+RtVHEZwN6o6HNfuDIIa2/nQgvbVb7XDQJQ1P4CduTSp5ZQZZUQJlvezlVX4P33DVPtSlve2SX4fzO2RnL+uhF8=,iv:ZvfGfS0B0EaYrRBLffg0SmCbYV8P3xiuCPq/xBBDi/s=,tag:4JRXzo1N1rbycXJkVEAY9g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
