apiVersion: ENC[AES256_GCM,data:zKM=,iv:faFGDWj+vd/CjVs4nSdbslJciCSPzPUI/rvvxhiUYMM=,tag:ONUPSnIqztED/jT9sKSdPQ==,type:str]
kind: ENC[AES256_GCM,data:4yLoZskA,iv:x83lrEksV15WkdRPWi2o7ThGPZ25MnSd5IvuZ4Xrb+E=,tag:YS0I0ndkHgky615aYymuFg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:17EwJSqfQWrDEpgqVi0=,iv:MBCxBgsV1+gBrs7va9Jf8NcTn7pdmSg/eWTunSiFAfI=,tag:V5vcUi6wM5urMsb75cMI8Q==,type:str]
    namespace: ENC[AES256_GCM,data:QzWsxioYgA==,iv:gioSyDRf7konRN/r8B0z52fFCZbyOr8E7eJNTEM52ZU=,tag:tYW0Tyww7C8fTJH93vZFVw==,type:str]
type: ENC[AES256_GCM,data:fQ++L9ov,iv:WS+B5tPE+S/uZTypLMpwQcRWNLBUhB5MSw5WZ8iccNg=,tag:Vea+kzHRrG/JSvRTB7JFsg==,type:str]
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:0XGVPNq60qtPZASqKYKVa9J4kgXZCA4kvJkqbucF64qBunN1KzsaVWOVTYu5r4IsChloxluyBy9jGrJHMEdyuuVT6vWbArGlzb3MlFdiC9kzFeSmlzRfOGpb+EhlRLtEoOePYGgYSi2z3dqK,iv:p2WoEHClE+MyIdCRWkj+gA1f0JMwGEts4vvyuMzYigY=,tag:o0HotWe6YOBl1XvqbgP7Aw==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:pySmTMkhplR0Z6DceOD6KJp6kq2rFqrgvruqe0VMG1dDeNTFF5vdbhtdEg==,iv:ZXjZfT6sIP+G0gWTpW8zCK/bRVphyMECW70wpD+ZPpc=,tag:8Anet+HCWHLZLzRfN2LaoA==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTGxwR3YxYmJoeXkwNzF6
            MWhNbC9wSmFyZUlNUVFWaTQvMlZsUFYzQ0RjCnJPTXVkUWJVWi9lMjZyazBtMjU1
            WkdjWGgrMU5OZFkxMTRGMnNnRjAwTk0KLS0tIHprbEdKQ1pZMG53S2JaWVJGMXFY
            QU95OHZXZy8rNUN1MXNad2h2ZFJzelEKLNWFDwEZ+DBXSjw8uZwVfB0iNpp8X01+
            ZMuTKMrFupsorre/Fnmn+xCGmnykMUZDYbxFZiborkP8Ml98Sem9lw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-15T18:41:22Z"
    mac: ENC[AES256_GCM,data:bLz7aumORih6bscsxoo2jA8Sa8nO3eym8c9JqRT1zbgUzjnpTuIXpKOIiGjnS5r4WGcXxGWDs+MRrZvzw5p8xgfgMAkSOQEiQdQPdd4b/yyshG0hd5D4QjwMwLpEqFwxOrKWjO4pZOr+QPHRZBcE5OZZnW51pE2d5XBuW867anw=,iv:gIQAtlBpT3SKdWJfkIIDE+AYm0En0NxpHXdZgUp3t1o=,tag:KBTJTKmNEt3zEe9UOdsFaQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
