apiVersion: ENC[AES256_GCM,data:YeQ=,iv:wyz2KdcKfCwCs+4OhWw/C+9km7CNmsFK+cpIy+rk3VQ=,tag:T7WDLiZMc1aSgFSRGWGp5g==,type:str]
kind: ENC[AES256_GCM,data:LdX88Td8,iv:4SI9cSxOrz8EAsTgrD6dTymOcn0hDErjI1+USakbx6Y=,tag:CmGXvg1jmnkk8zmffMy3hA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Jdmi9idhbVSqvgM/,iv:wl68+EnECyEwNN5cXv8jGKdGRj6ba5kr4cnbulu3Vys=,tag:Sd0oKb4pdf7gFMSsh6DcAg==,type:str]
    namespace: ENC[AES256_GCM,data:x+7pmetvcbE=,iv:wBC+s9TLvD1SJKdDeNDLams6GeqLgXTPHHpe0CYqa6E=,tag:kPb41E8zpgaOXwQpu9eOCA==,type:str]
type: ENC[AES256_GCM,data:Ohvq+M5y,iv:E7UsMtvPDj3q1FuE0kD2SrQ76pHvCBEpvSall61kyYM=,tag:i7OS6f2sdI+4eSR+YJPaIQ==,type:str]
stringData:
    jwt_secret: ENC[AES256_GCM,data:ipYBRKleMLN+qEWQEk+nMmHEBQsfja5kaqtOAKqN+QgubKjONDCMGPy6VrAfWyyv,iv:g+GLyJq+X+CkRuC4mw3JtpOE0vjfQXHvEZWNcfCOhbg=,tag:Uo6vfZasTS7Y+ahOQ+3whg==,type:str]
    key_seed: ENC[AES256_GCM,data:bWJJyYpkeGF+wbfWZ2IuRQiPULGs4vQ+/RvjxBI7OAlII1RQBl/xGQT/8EZg1fhR,iv:Mjs+zSjizdA7fqDRxpSCh8lAxsJYZ9DpkoHJLzbMz0w=,tag:QQ6jgYK7b4T9RV2XAqKE8w==,type:str]
    admin_password: ENC[AES256_GCM,data:EbP9mm0Wj9M+PVmBVzVnW4rNTUhOnBmV,iv:ULGl4HakAPFIsbmFAUDgIcGrG9CZk8tbHWY8oPIQ8kA=,tag:e4yaueioacjVgmL1u7/YkA==,type:str]
    admin_email: ENC[AES256_GCM,data:OP2QrD6vFUIS+3O565c3D38O,iv:AfF+/FBOjeSSStlS6U82JK86jkr+RhJKuIHZsB9v5c4=,tag:Re8YTImYBNqH/SYKCE5FbQ==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaEZ0N1I4TWZxc05SVDJn
            dWJYV1RMVnRYbEhsWWtJTWJXb3lJWGZuNUc0CnI4RHZBbEJCL3ZDb0h0cFJ5aTd6
            MmY3MFdNeVRGamJOc3NBeGwrZEZiWmcKLS0tIDRZSmhycG81aSsvcnVydSt3RkRL
            VFlIUlQ3d1ZBTEUxSjdEdmJrV3gzdE0KFBT0U1Taxp02+brENgJPC7xJGFzh33Hl
            FqTECPxZVhnpKvswmzO9Pauo6l/Ykf13+w+Xg75Zunk+Re3KT+s5Zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T14:17:54Z"
    mac: ENC[AES256_GCM,data:E37s8iuhwq6Z7LkdA8pMTJ/x1P5CETACVlyKrKwB0ZuYejWT5m8YYnLxLuCsadddgO55wu963WadE0Yx5dfrLskkmUphl9od+xYhhQrq+QXgY6wi5Dt/uvNxn0gkcqP6u6187jKLm4BCLT8JI9xv8Kvw03tKgWdGIPJrMdSZmxo=,iv:upKEFecKX5zUW0KU+B36eGbMaplPG+Wn75pXAwSH5o4=,tag:52lXEIkpvKEE1nYaaklBlw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
