apiVersion: ENC[AES256_GCM,data:WSU=,iv:T9kX7T5wuNsHieshgteO5SzGn4m6Y7K83z+pUwA1P3g=,tag:w/RGX0nl95d9ZeiAmUVJLw==,type:str]
kind: ENC[AES256_GCM,data:mwqAcmj5,iv:fFNwnbeuDysj3lV+9JrL7gXOWgOPcmDDM+pCkGZdz5M=,tag:JmUQGccf/LtG7Kc+Aq6OkQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:RPJzPdCtAcUk2QncP3ViLPY+CU4G00Yr,iv:wpC8ET1rEPzf/rezsHiX0Rk13r0wRTBzFFXKiq1IQLQ=,tag:z2wHQ90WR46Ls7fK3BTTZw==,type:str]
    namespace: ENC[AES256_GCM,data:iF6PzFyioyw=,iv:C3Kd17OtWuaQW8r6KfaZkeLdeBpfkH5hG5cCOvHJFQY=,tag:6SNmVy8iArgPWeADeZbEQw==,type:str]
type: ENC[AES256_GCM,data:E5fwvZ5H,iv:KF/vKbA94JxfXZiRrMUMbR354i0QY6m0BG+SxAil58M=,tag:g2LFKLYx4o8rMjC2oB21rw==,type:str]
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:t1YrlpRU+B5vtmdnVzSYp3IqDDQ=,iv:TWHhUxVNTLedmREla0siEoKbfm0jzePgbOXvjz0Dcwk=,tag:aYkqJbqYB/8Z3D9/c01Y2g==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:55Bh2QGAdvlbi31bLFsYdVDCqpqPpeC4shTAeVV2Tp6ecdcPdH6udg==,iv:n/oEitxHvIf63zIJTXwXm2pkU09SUacm1aIL6zfARLQ=,tag:XCbok1wWw7d5X9E+ZikkBw==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZk1seDRRTzFXWGM3OEZ0
            cVJnVE42QUF1TWhnVFFuaEgxV2tJL2lxRVEwCnFTdWRlZnFWME5tRGhFV1hYQVAw
            UlFHY1E5NUZ2NG5IaVlzeWhQUm1VNkEKLS0tIFdzdExHN2p0Y21uVTlXc01HV05n
            Tk40UnlOTXQxVlcyZGlLRm5BK2Ewd1kKUeNylzGRI2VDC8Frb4l8dFQeFIc80k/L
            DPijkkXFd31GMmL+RrHFcDj4mKao1XY0Ue1SkwzpcbxLaXdzQG2XCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-22T19:01:39Z"
    mac: ENC[AES256_GCM,data:LgunF5OmZy+w6L8h4EYyPXKFD6pA22Xb+bu2d3pNzPoS4Dw/JCXVTxYM3RAitfV+mrdblFPg+WeiQnjVSaQY6XPNJ+eFXLNXgg3hxLmjzi6zdNRtVuot818KsPgTeZEsabTKpB+6dTN3Y+FPNdD0P7aHCWxKWDCuBkvwRHhpajo=,iv:8EWmrcJm1FDHecbR1ZJYsdzoqTHILLvhRxsS1O0sYg4=,tag:7um+1bxU0sUWGQbKWi+kxA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
