apiVersion: ENC[AES256_GCM,data:QN4=,iv:CHF/kg4Ifn57vcvIZ63RRzZLj/TpGIopSSWHqFFmmQs=,tag:X04JL2IYdx6MvW6TrKuP8g==,type:str]
kind: ENC[AES256_GCM,data:KnpJJAbh,iv:h8h0pgeLy5O/6yqhoVAlelzVPBM0V3qQ8CUsWlgFxyQ=,tag:wrw5SvOxu1O7SGs/m/fnlQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:GO09s+78yynASMIWOSN/HYSgfAo=,iv:oZFTTutvZ6/huO/2fQORmIp3xaal7I/TisS1t9OVSNg=,tag:nEmL5sSA90oyFdsW28A0rA==,type:str]
    namespace: ENC[AES256_GCM,data:YebvW1L6,iv:KjlXYia78igXGNQ4oKzh9pyJPimSgrabPErNjvp57x4=,tag:A6kg8desSpnTg3+p+0dXrw==,type:str]
type: ENC[AES256_GCM,data:cITiXUlS,iv:vRRRRPwrnm95rhPrPfntx3degNpCqIvKHojnqdfDxFM=,tag:GMVOa0KvNyW+lakCDWBVJA==,type:str]
stringData:
    accessKey: ENC[AES256_GCM,data:NCj2Z5iebR21jE+2bKrHBFrX0Vs=,iv:DlEDnkopbZJtfMe6nVFSZcmT3SmX9ysX7bDguVt+/uQ=,tag:OBVE1ZJJsyDzTM9Fq80IAg==,type:str]
    secretKey: ENC[AES256_GCM,data:sYkPmePdWocI5pit50ohOzfHCVnau018mB8PRZD3QgzOQySB4uozZw==,iv:cGNxWoipbIMCC3jpk+aAckuB7JDSBjLKBLa5/G+Xizk=,tag:7eEMKINxnjx9FITziOXs2w==,type:str]
    encrKey: ENC[AES256_GCM,data:E4nTuJcRWO9z0umc2QV+JuD2oMqZAUs4gXGw7i4XrXCDgGiLn4dAZB42i/Q=,iv:R8Zl3leYl3s5hNxbLVs5RGDb/gGf20c/KiRrdlZ7IK0=,tag:T1vsSu/bBvPUx4h51LCIqQ==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWcG1peStUZitpZWpWanIr
            eWlVL0Rha3RkY1EyeTZSeCtHQ0QrWnpRMW00ClEwdk4xVHJZQTV2dTZXWVp0NWJG
            cGVNd0VFalp3VUxLUURkNGIvY2RzSWsKLS0tIHpMYXYzQkEzQytURnFpZ3BmeFVF
            c0FManh1SFJsazdudmo0d2NUaFpObEUKqtyqlGpTA/RYy/CFt1PQY9d8IKLIuOpw
            SYRPLdK+yLyxKiM4SIP7s2lFIeLHaGz1CjjDQLXnQTHM0tcvv1Bckg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T02:41:25Z"
    mac: ENC[AES256_GCM,data:dZeURP0+/kDjaIlCGvJRfB2bG5dShVXWe9KvB38wpK5vj8I+t94ccWemfspZ0zH3Y5parQ+m8FtwO+JQZ1fjRd4vnDqFXDAXiojLo1w4LpPjsh1+xsA81MwJG6pSkdXv6FvGuVgmaP/aspESpqyDdKlmq9LTpZ6KrwU5Mx5IugI=,iv:SClmnREdzIRoEcpY6WfUfA+S2LgQf6VxfM2lD22qRnE=,tag:jLNjAWPZ9L2Sb98Bwkdv/g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
