apiVersion: ENC[AES256_GCM,data:ImE=,iv:7NYb8ZogW2rLW5e55UIYEFV1b8TduObWWM/VQptiZy4=,tag:rDoKdlxWUWYm4c/1i4n4qQ==,type:str]
kind: ENC[AES256_GCM,data:LNBTd/z1,iv:3p4YmHCO1A4ffJfXNszdTymiAJkQA3tZdk1PT4rxcTs=,tag:5aEUoBrzoIz5S2Im5oCJMA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:P1BwUnUIdm1lnCZATKC6wLnqlRRb4BY=,iv:Q3pnC/nzVsCSA2W4DSaFUcjYTXQsE4RLHjU29fViND8=,tag:01Bikny3rQ3+HDukwmP3+Q==,type:str]
    namespace: ENC[AES256_GCM,data:9oWbziK5,iv:Y0KIPW4TArmBNJ0rLGEHT0L/nl3+Skijlg1zF1Hi4z0=,tag:wfeoKanV1nMGzdT1LLJ/nQ==,type:str]
type: ENC[AES256_GCM,data:ddBgN1Gw,iv:czTfNggO7uM52oxLmE4hYEey3wvDMTjBhNmJ/Fof+Gg=,tag:ZDmusqe6i3ubuo8PBXFDDw==,type:str]
stringData:
    #ENC[AES256_GCM,data:fy3EU3e82AhjSplQqRVq9ngyUXTA6JujgYa6XDci8AaL+Mkg+KqEKLHVIsvsNQsQDJZZ3bDzpcBV3RCskU8GwIyYPF9cb8s=,iv:h5QoAbldPbT7o08OgFrwiD+LXtdf4crGFGdyMPzqFRY=,tag:Xjlb5dyZ8k2c1rGF+PxB+A==,type:comment]
    MEALIE_API_TOKEN: ENC[AES256_GCM,data:vpU37uP+9JRqu5H2SQDeeNVLvVDbn/5EebRksCcV8BoBFrCVynLbh3uv7Khb8h/UyoSIO4RKfftbq2at/6hsKlCDCby5I9ugEmbtp1bHCYqDumCfZVOkHhjK8eNrH2+W73HJ5GR8ojDcq8Up2mqkj9fCNdg7eFHQpPgKaPYJ4b3l1ggJ3ElDyiFTDUcGcnYq46xBPZECdl1vL/tSlOQWPWN1im60PcW8UgDEACHd/HbG3zgSdeSE+AAbC48TicKQkIk/ObMEdX5nSdeK3GzwAZ3ZXK3Cm3CNdBu8oru2SPWdpI9v34xiNmQ5x2rdkat6Bfpho1fEScncAaOun4TxCVw9EAWygdPPpFW0IC8SEQ==,iv:A4fbfiO/MUPCrJ8HRVjmdAmEFOX6MgyBINK1TxNQlts=,tag:2O8YdkMyWiXMtKJxJaj0RA==,type:str]
    #ENC[AES256_GCM,data:ZVkCsfD7XVzq9lxVIl5rQ9CMR+k=,iv:qwP1OQnDVb1ta3lxzSk0sHAKt8dFoGlPGoDEcm2xyPY=,tag:JH7vrZyE45CC/B447qD/RQ==,type:comment]
    PROVIDER_API_KEY: ENC[AES256_GCM,data:HPwKwWbN2/7sWOVFhp8N4wOEFdBTSkPYWml4lwSoN2O/JcI/+lusXPWYrU7lAs7tJ5u8eyjZOnt0rov21vMQY0yCKg==,iv:0YO3uUlJEOQxKxhdq1ZPQLihYZal80Tn1eBRGN3GQIA=,tag:k6JwY0vBWLPwVDciSVv1Lg==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhL29BY3duVERocUdRWVdv
            NXhLeFJ6cVdpOWlmREtjSUJaZ05kT2N6TzNJCnFaSmJEVlhXaEliYXRzK1BxNVZj
            SHc1YkxJT1RTbTNqRlJOdEFKdG03UTgKLS0tIFgxdW16SlJwdG1tbHF1dDA3dmVQ
            YkJldngwb1BGa1lkYVN0dWY4Tm1YczgKOglXpqVWMTsaqz8GRfUxwVbnzCgXaNAS
            j7CS9rLbSTWjiLOTXTwkbj9I/GSJSmPdpnzz/cH7xw6T5sJ/4TYqGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-09T19:11:28Z"
    mac: ENC[AES256_GCM,data:KLjA/mfaamXw6dpqh+LRmf6lNsvoyQeDdzcKxy1tZ2uIWugg9+JHhRsF4cvHHF554BqGV0d66MKtvuawZUcPooxfzhSFcOyjfMpUupg1YZl2npZGQtT5tb+lRTFH9X1TTQ50ExTGZlmArBEarZwyNxiVkRaodYqNnesZm5llu+I=,iv:meJ3GAEpAupE6Ar3hjke7PZ0jv6G3r3a+0k8bt568RM=,tag:byY5y7N6L2VT8IX8MWoizQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
