apiVersion: ENC[AES256_GCM,data:yUM=,iv:z00dZT4XCqYGcGsjJIUdCK5VKnNM0QUHpYX1jfcWuxQ=,tag:wDjASu2PQygDmOmvoKIYYA==,type:str]
kind: ENC[AES256_GCM,data:a7QjQtoG,iv:9wJS/53r3X9773pRWTVBhYfcqIpuRsNmUwDZkvD1KsM=,tag:3LVnzhWbRKd/v7lWe9GTfQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:l3QpbAdlVzoL62RuPBGbWA==,iv:ZUWs0NsHCURSlm9wnUK2cXsFkt8Mhdx6tg/cZO7KClM=,tag:+U/S4U4Kqy8B6hO+62/6Dg==,type:str]
    namespace: ENC[AES256_GCM,data:+0zUg3yL,iv:pZTz8A2I6RyIYv8vfY4vBCMGZePdyb8NHNvM59k4uUc=,tag:YcemYrRvf/tXG9QKyhnN4g==,type:str]
type: ENC[AES256_GCM,data:iJfGDpPw,iv:dImkMAKQhdaErZAYU8pm3jD4Mpq721krmYabAm1D6d8=,tag:O5EqPmLocHYPO55tC+y51Q==,type:str]
stringData:
    password: ENC[AES256_GCM,data:sazk+F0vilLFff/QDuryqGVF9nYpSWSbaGiC3KNfxgE=,iv:r51itwNjJQrl9LhPoLqRs8GpqmWoCnqjiZoC6L7xVbg=,tag:y15O39vMPVvn5tV/5ybsLQ==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZWJjSXNnRGlYZmR3Vlcv
            eDlXdFgrZXFBV2JTNE5NUndPdHg3dVc2U3lBCmtLVzl1dUNmcU56UDc4ckhFZUUy
            ZlRieGZOeXlmbUZlK0xWekpFVnJodFkKLS0tIFZTZHFlVzRiTXJMeFdOMVZXYjJE
            MWNhdXdQbWxzdWVxLzNjdlNuZ3hFc1kKGaEml9XDw/YhgIkbSyqYctHSEpIn8Zki
            DIoAWtsdzuPrVBrBRrwZrprW60gDG3ui8o3EtcZQn3T+yuvYwROOXQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-22T03:09:15Z"
    mac: ENC[AES256_GCM,data:hR5FyaRED0j1FQE9lSTpv0kHgc+1pkicH7VKSHRIo9aCxeGNl0uIjKRB9FDqoFb4+I85Jk4boXGVOAnARcSMmgZ7K2XfSFht+c1/hN7QYlQJcF8Jgl9XZ+dHKFSXFcHAORasFckXnftLZrGAN2+pV1QOhS2WGPeeMvjCyHiabzA=,iv:+5kbxWqPeZi/8AXUbPtvZeYfxkd2hev260MxNmU6DSM=,tag:0RuTua+SWN2iigJfrX+ECw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
