apiVersion: ENC[AES256_GCM,data:O4o=,iv:pCxgmp1Ol7DFUM9oc6GB9moDpIFXQ6H/6VcrKIcoHt8=,tag:K23pBSu5OKYWabNreIYsgQ==,type:str]
kind: ENC[AES256_GCM,data:zh4kPHOC,iv:zf74CnfS7GgjyA6CvKrJvbFAWRrXD85prRVM+qaprEE=,tag:lUOV7jJ8IjVYS8VGKvunPA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kku8wQZ8NX0Vg0zmBlrz/oboWuhO0vDn,iv:jPZaVA3UyPhVLomY244Ck5H5ye/C639ZdyX+IiBug5k=,tag:SywqHuVz2uws587z9GRXVA==,type:str]
    namespace: ENC[AES256_GCM,data:bsnmO32m,iv:cx4oiyS3KknA61NE8WCvWyqkV8LO1drGpxtVz0bZixA=,tag:n4xXilms4af6TXGXQiDIpQ==,type:str]
type: ENC[AES256_GCM,data:b+9bZKG9,iv:7R6q9Nj1hBthnpohv+neKyfprYxD7UxeAXDVkB2veBs=,tag:jJkUmvT6HwaNBVZOhOhwMw==,type:str]
stringData:
    MEALIE_API_TOKEN: ENC[AES256_GCM,data:LL1nR8NfgjPSxhd04PyiLOafWuVmrIT5E4rZZwH9WTYEiOVDa3E0z6MeVAspOtYarJxKBTkBRkOJOjT7psDOaR0eKWa1G0XJFE3wqLQ+msKU0j1psFnU3+feAWKOUdydjNYPgkHYJpRLhGbHnO2iAOYKVkOprnjd6q+NxF1KbYfY8LIGXJvDLCbVIwvRCy1RHwSJ7ULTFgbwaEBqJ3J8QRcTDK3Mu5h8SQ8otwFs9r/9xuRSN9KKMfvgKwGEYKWALrXlWL1aNspDpWkWDo1euxgkNiwKOZa+0jCxXuEE7b4CMRUkucOxnwv40AXRfySwq9tsBRXX0s2zzOeE23OLre8hLqc=,iv:jFHO65knSsSrK0ny70UFt6UO6AnyLoVJs4ww5flei8o=,tag:7pu+gj/AtE08QfGSkWLSvQ==,type:str]
    GOOGLE_MASTER_TOKEN: ENC[AES256_GCM,data:Iv6srGMu6UExjSWyKZU1OxyEYBL9q5Q40coGKHdK3v9ACbOVcFE+VmbaIxPjajgdDrmbc8LOW5ERkCz0An651TgXiHhEFX27fQBDVfjE343J+gYVt98ip+ts0oJ4q+7reTkilOmRyNC/tJx50wA7mY/8soyJZKJf40oBr6MSP8j3aVxZ/l02KpBce18GxH2FJCHco5EiIqK6ThNuzGdkGs5aP7zbebvspXz1vsXKoKSqOdZIScKXbo4WwyOyO+3zaT3e8Dkv1YkXY8WRX84EUXYz8k0kdKBVaJIwZ/uBKQ==,iv:hl6PbWAzhxEjc4tKbGyRq6vrDoM0uZPtIkgkRnLe/FQ=,tag:uKhVp1sPC+FoE8l5fDbkbA==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMkFhMERXeDdxaGsrN3Ez
            aGowSTM1czNZakRLRHRjc0ZZWGZYN0FabTBFClEwVThaSS9LMkhCMW1BUTh3c21z
            eUUvczd6WkVBK3dnQlNFMkpvKytXaHMKLS0tIFQwWUwyWVNxTk1nOG83VFprSy9m
            aDdhTmFRZWdYRzVHQnhUTXZZN3dJdE0KKr1rPn/vMh4FRJ3SpezV/ArZ/bhHr6L1
            +0FNphpctGSm+pvIDHCTaOsEvtBYbpcXwrmdOGU5QDzgnObWtzaBFQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-22T02:40:58Z"
    mac: ENC[AES256_GCM,data:rVY21hjCmkgKMhu24uZ1ZaANdIZeg2tRAyO5C8fgaVKiB54+6khzFj9ggsfbffr4Da1RhCL7t9B31gQGCO1HPgpcNfiqijFp28qE/xoeYuSJ0WiKKLceCi2JDhc3/w4zA8gQWp53jECpCLFgHJo6OghL/JXvA+taFXnwPJ52R6I=,iv:gx8RrPKL3r2bfJyHgVGvr2vyk+edKhRM2zJ4kGDL0r4=,tag:tzPOZjbm+2Y5vM/ZRcADRg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
