apiVersion: ENC[AES256_GCM,data:sLI=,iv:oJGVHKKq+DNOgYhkfcyTuBIiBNOKvjgjLxS5SwZgRUI=,tag:eKoItR0Cc5iplvDoS7QtVg==,type:str]
kind: ENC[AES256_GCM,data:NTQKQz2n,iv:W2buu9140Ha9q0r+E3GKYi0mX76pa0R2hoR868dp/Jc=,tag:jEtguAvS0Q8IrX2x1RMOmg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:jCz6tJE9ZBfnjJ3e6mQUVr19g6A=,iv:z813HWbMU8baz42egNyvvLx5huI6RF+v2DB+J1WZWAE=,tag:TEkmwmGjjmEmrgLWJeEHcw==,type:str]
    namespace: ENC[AES256_GCM,data:/RqVirIY,iv:O+OER5c+S/sjFxPUU8ive+tNSEXx0fHE9Y41qaGumos=,tag:RzNK5hyZbPPQM2nXdoMdfA==,type:str]
type: ENC[AES256_GCM,data:EjFY6kqk,iv:vflmtaukhCrH3r4nO2rejHa8Z4sfRRkkJYcwYLY1vT0=,tag:qWY223bLr2ec1iBrRFU8ag==,type:str]
stringData:
    accessKey: ENC[AES256_GCM,data:Ww/7It/v5HlKGiDiphug+5ttfAM=,iv:1HEK80pecqzrHO5EsMZCJTPlzzC6OGvtV9zgM7Ygu5Q=,tag:EqJP90qteD3rVYyMif5ufw==,type:str]
    secretKey: ENC[AES256_GCM,data:az0HzpPyyY0kktZvwfdh1Oo5k0Z0acEKqfGlY5UIcnP+Adgy8DSIIQ==,iv:fA1uVLgEUakf0HbLhOYumC4F1GRMLK2d2xzknVIIwgc=,tag:kCzy3o6o8pEi8Jo+8eOF+A==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrVlA0dVZrMVJhNXVBNlU0
            NjdPRjdFUXpCOFlkeFExVFV1OFpIZUhZeUMwCmd2MERKQTF2UEdxaW8wcUo5a3Zh
            VFk0MlpEekJwZDJiYkczdEFpY2djdVkKLS0tIFFQQjkyY1cvU0ZDNDlOVDA3NS94
            YU1wWnJ0ZkhHeG9jb2dBKzBZcTNCV2sKBnH/pJi53IxjJgrqiScp7W1Z2sSSwWWm
            sq6VhrDZC4lKlosbT0qdMFsSQMvE9BWCat5+s/IDH5oJYw2H2tz8+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T01:47:27Z"
    mac: ENC[AES256_GCM,data:zt8LtPNMnw+vveN1NZ4zK1A08aj2yUnFfSOFetVCTDi4ykhVCV61rjjWiHZUdAJsYErULxeTQkYMQTIM3L2kk10zkPvfADsmQSmU7oG8A/VAOh5tRFipvtM6xkyI9emIeUJkwdFTPr5g/gUVFIaQI9v9G2nhJYngOoFPPkr24u0=,iv:VlW0cWre4hgMQ5stW9GOKIErxbrkimu6HcdJ6cvG2cI=,tag:ma3troK2a91mpkLB9iSDgA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
