apiVersion: ENC[AES256_GCM,data:sP4=,iv:NkHZPk3qiHvjvSXJwNWOt8Hk7LwJjxGQVWk4Qtg0Gw4=,tag:/fBTig/j/eiDhP/SFqdIug==,type:str]
kind: ENC[AES256_GCM,data:zZ/Z5c7o,iv:6zlrPe/sPPKdbyVPjv9qzB7No+5BejgUwTkG9i63WTw=,tag:Ug7U0NSSoVnvucimzE/XKw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Ui2pMNuDLe62iaRjPMnRRU8x,iv:NEeRzJKoZabCkqYOenl2hHeKFMDM4khkBe2cIuS2B0M=,tag:ou45ostZJ0/OU/20SKbqzQ==,type:str]
    namespace: ENC[AES256_GCM,data:Hgp+xA+H,iv:4R2WdHvtJK/ORpS8HTySWwMNhNeAGUkxtMmCPMmIeKQ=,tag:kVyAdccfxO87Rx92Ai8Nww==,type:str]
type: ENC[AES256_GCM,data:Pey84unC,iv:XkCdKIefjOYAzys3yzsWj/aMySpf/knfZRaMoWfklgI=,tag:CB+JKgvptiChXoKqPEcl/w==,type:str]
stringData:
    clientSecret: ENC[AES256_GCM,data:hCvy/PEcJhfhQX7nTs09ysR9O3+Kw7UUoZL/pNRjePFAvLAR5A8MGUqKXfre+1kv,iv:q17bKEdlvc3ctDjrQYSpwIr28HCM26LxpYyWKUETtak=,tag:/+g7vvnada3pdQNdYwpoSg==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYW5WTnlQYTNXMHFheG9D
            eVdlb0gzZ3k1SENKVVViNURMbm1qNVVtTDBzCnR3YnVPMnBpejA5SWg1NGJ4Q2xM
            NHdHazRMRk44UFp6QlY1KzM0V2Q2dlUKLS0tIC9BQTl4Rzk2R2YvWXFYMjB6eWZv
            V3hoVVRCbzNBZXVHMzRzYkpsaFZwdEkKd8PmGvnfDDFlT3x/ZIseRMu+SpfcJniW
            MJZSy/y9wIzcPWiYRoOTuvdtOv/8zHi6/lqaoj+kECOveg1UeHSiUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-16T20:25:43Z"
    mac: ENC[AES256_GCM,data:6D9+nZShnlKZxzXzDbvizTq1cWfBNKGBKE+ijsv21m7CYx4LpKAYhWQzWe9tr2GhNVPhaGPsgUHVBePaEzLCldq8b/rDFJDdsZsNKW4PomCXLjD92cKI8urZjoxAyqTUQGxzBEr81A7mWcL9pL9aePw7bZ0LDT7rMohLDoz8FPc=,iv:aKfOTVycw99G3I2t0hDJ4hWd8pISrkjTaCXSv0hjFPY=,tag:1n1ig0FHkxuYqWPrVoQzuw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
