<<<<<<< Updated upstream
apiVersion: ENC[AES256_GCM,data:MDI=,iv:Qu2oFQlS5wjke4FXpZH01n+7a2JHG59NLNP0Xa4S9t8=,tag:N9Stj3nbGYYilJIopD08GA==,type:str]
kind: ENC[AES256_GCM,data:kkX8UfNd,iv:y4zxpQLSRhOCJH6LxyMo1oZHPNbT/jZkRTcTZZsx/K0=,tag:V1tGQL3rgBvoRSOYkKTOsA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:g5URKxAOYkGLOp3k6dRyl6j3wcM=,iv:Komny6aCdkIiJJNd+X5sZaEST3VbmULjkpQWTY3mDao=,tag:Mudu9zq1AydP/1WIZfvesA==,type:str]
    namespace: ENC[AES256_GCM,data:B/qaZ5La,iv:I5x3RfJp9Zb4BWiCgPPBEro4pYWZaFy/9ZKgoMh3Pjw=,tag:HX3PwC7GtU7yhAP5DCb7Cg==,type:str]
type: ENC[AES256_GCM,data:Ik4bbxss,iv:eGqvE30JDHPw4/VQ6msTyBdDFMy/hjaE6z0d0P9Qwmg=,tag:CvWwdYmYvKa3CMD7luoZ6Q==,type:str]
stringData:
    accessKey: ENC[AES256_GCM,data:nGTRmIkBbm7m7SLWhjQT3xs04BU=,iv:tU3VMx15ty5M6ovyZvdperEUNcYX96UcinWQBzyRYoI=,tag:cP1is90M+gt5SaI4kjpcOA==,type:str]
    secretKey: ENC[AES256_GCM,data:FvFUWZ/JaY2m4p3uYF32K+A9Uxk++HLpUEwt7CRWq3cNh5+b1u1Lvg==,iv:xqfCEEGLxd22nRNDYYf4BWLvzZ13LJH8ubjdwJbahYQ=,tag:vkSkXmqBh3Bm/Kmks3j7Dw==,type:str]
    encrKey: ENC[AES256_GCM,data:wgxY/e43Z0zebsk/nEIQMJ6wpJEdt1iwoaBWYvINObiIp30BlzRDEX4i/pQ=,iv:dr7hc5doZHt8a6OFTb4qaSNxEdUFMjmJLV1KBqUUGBs=,tag:/PFk/suxiS8YWnFDdi/cpQ==,type:str]
=======
apiVersion: ENC[AES256_GCM,data:Zds=,iv:S7qyPy78bzUiLabxNmqhD1JI5FyYigfl/sKAZmTTSAg=,tag:8LtAGKXWJW0lxh8lzL9UKQ==,type:str]
kind: ENC[AES256_GCM,data://PiYPYc,iv:31RHXXCPKEcrvGFKvxDcxQ+ctUGbIszDSCRILSqeITs=,tag:LdcHarOKtTZk/o6n6KU9Yw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:8ZapZl4nZuxcElWpma8MzaDy2A4=,iv:DALYmmj7JQ6F8mwkb5dhRPHOEk0Ek+3ztnvMr7eAR/A=,tag:/+qM2MJDwl7nsJPvaNc2fg==,type:str]
    namespace: ENC[AES256_GCM,data:DrpnK5P9,iv:kfNtSDSEAojF61wqYH1EM8xOYYiJnImLY6J50ecpg28=,tag:u7S9f4mmYhim5fDpLq/3Dw==,type:str]
type: ENC[AES256_GCM,data:tVsFuIpA,iv:DfD5m3Ueuf3Qrb12cEJ/BAGWr94vAk6lqSi/n/Q5I68=,tag:2K4jDCD8sks8tFjpDRC9yQ==,type:str]
stringData:
    accessKey: ENC[AES256_GCM,data:J0V/gQeEwNRLd6Fw8aAWOil7aWw=,iv:3iVhX18WbGW+4Tq1+JCC9i5KHuZdtaYIpVqFHrdPtUY=,tag:5yPWbretXTWG2Gv+ET0hRQ==,type:str]
    secretKey: ENC[AES256_GCM,data:WU12M5rrPWGaSoHwv4gf8uR/w2vqQpSBEkFGiSorv7kSb1jLRYQCMQ==,iv:QFfEXGESubFNphPh1iWR0rtfH8w3stAtTKRozPa82Ts=,tag:UKGfTTrQhMtQNBeb/NFJIw==,type:str]
>>>>>>> Stashed changes
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
<<<<<<< Updated upstream
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MDhRSFZEcG1UKzhOdk8y
            R0RablBOWlJ4MFA3OGI5VE04WmhyTTFNSEdFCnVGcUVqY1h0MUhaTVJlbC8rU2Rj
            YndjT0Y1WW5icExtbGJwMXRMUFA4MDgKLS0tIHVEdEphVlBtcjJOd3dUenFEeFB0
            SFMxQXNXa0l1UlBBams1Vngrb3JxSXMK09LOw9KTKERXlSkdhc2mqYlBVrCBZlly
            qkZSfbOg6ZiEQJ6kUQXc12Xt0N6pZyaT1oeapR3fYwYNO9s29b9pMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T02:05:38Z"
    mac: ENC[AES256_GCM,data:QL90CXE01vJIIqRRx//jmZ/vL3NsE30pcxj64E6bYAyu6RL5wHNSXKdOkuJmEXeR4jBo0Rj29x5pjt8+mZATT3bOdfqXykoIeW8Uace/y6Zbk+1qI3VF2mNod5c8JX5A58UAlbbf6oYI4lygIrdm/ODNyJtrl1Z0zeu8OwgrmYw=,iv:nSGly4ZIJ2CvofPTjb4w8q99F92HzQFmlTbYvIcrhSA=,tag:kfp9X6d9dKA93pIsY06x7w==,type:str]
=======
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxV0lYUWRZL0RNZ2ZMcFlP
            Z1AydGpKMlRuTWNTdlZYOE1mL2dtamw2ZDNrCjRSekM4KzAwV0ROM3ovRkVBSVk2
            VENyOGVuc3hFRldtNFpodnVzdGdjREkKLS0tIEt3QnZKdFhsSXJoNWM5dXNkUTdy
            aUNBZ1RTU091Y3BJVExIU0xIcEl5Yk0K5Pt4xDfHf6q+fAdReFgD6KkBX+uadZGm
            KSCAH2WFkgdP2EbtVBKJQEdKynqhXFQSh1R4fUV9n7a2tqrRQqTPJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T02:32:06Z"
    mac: ENC[AES256_GCM,data:M9yy1jHjkSdmjp4yUPFkF4gFrWXesC1+B6yqOpfMpa8AiytMInh6orVKNojS4BputtcUoXATIg7Rg2PI9Jcjz/r5TmqG1K5ThwbSUsA71BG+pNis468mXBicoDjUlIgutkIEZACj6NXx2sfvKULhYPxGuwfAIzPhuQ5SDZtULX0=,iv:GqxZhwmr64yNAA8jGaqVtR0TgP9LHN9pV+1RIAaVe78=,tag:IyPO6L2kH2S4wdrc2WGE6A==,type:str]
>>>>>>> Stashed changes
    unencrypted_suffix: _unencrypted
    version: 3.12.1
