apiVersion: ENC[AES256_GCM,data:Njo=,iv:96XGpV1yrvvq+8ZfV8Nw27h54zpLG0vTWD1J4PFH+PY=,tag:+gCmbS7JMbfMJvLSlVnu/g==,type:str]
kind: ENC[AES256_GCM,data:nVJT4xvS,iv:m0syIXbHh00O5pM8f7P87QeOz3a5TKge+XkLZd/ikfw=,tag:rauunsc4Q33ovF202zcufw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Sp1y5yDbcwvl9OuYMIiOObRMxA==,iv:grWaRZaj5KK/8TfkUS0AN0Ivj+xnwGTisxKP3IObJkU=,tag:j6roQsCfVd0WMZvnCWe+Aw==,type:str]
    namespace: ENC[AES256_GCM,data:yw6M,iv:QKhmrGWOZkNJwmV7Thoo1D3mFZDiydnixc/mhPSx+8I=,tag:eJVgi9uQTKuD3Gzmu3jAwA==,type:str]
type: ENC[AES256_GCM,data:BseFBzVf,iv:wt5kBLaIH0sC3eY26sDmmyZGwGnRVUXs+SIIKqcmwHE=,tag:LLUy+4viAgwqOAU5CGilWg==,type:str]
stringData:
    client-id: ENC[AES256_GCM,data:4FprkL4fQYuIfgi2,iv:F5IDA2VJfPv8CiWBwF1hZvV6cnGuospdUd8mwj2Af9E=,tag:ReHi1oELEAifk1TZM+2Ahw==,type:str]
    client-secret: ENC[AES256_GCM,data:S2uif9IMxUBFBGnmmBlnmcbEd8c4QGh8Jkt8wMrL8e5zbPAssqbyFLfBwg==,iv:C8Bx0kx9g3C6kwYPtyJqVlO5wuRE6fA8+ENPp80Zi64=,tag:9pr+oC5wxUxvxUqwIQAkiA==,type:str]
    cookie-secret: ENC[AES256_GCM,data:T/K9SK9x9SkiySONrTr3F3f13nzhXOUDHuAKPb6t3fzZ8krPu/WT+WCx7Kk=,iv:zHVw97NJme/XRixnXoqgISi9NLdnXlNHh4GkfSjbFqM=,tag:qP0phiXWAERp6UMpftB7Kw==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByKzJVbTc3T2tQTVFYb3hQ
            dTgraFp5My9wajc1Vml0Zk1kRFhWUytFcUY0ClNYaExVSkJ6SG95WVhIU0RRdUhx
            Zm0xbVhXbkNIWWUyMENsN1BpUUNqdFkKLS0tIDVFeU9oS2plYllQaEhsbndZejJT
            MkxRR2U0NlU2U2tubDNaUHlUREduamcKOQKHzXkNc9aJomeDAynp34ngGoeIbxBS
            13fq/LzebWoE05MRNElzZc8W7D8Eutnozs4ak1bG7VSHU2YFdptCJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T20:03:11Z"
    mac: ENC[AES256_GCM,data:MP8a71+cuJOFxcaA2OjPGwPC4GdsOTOfdbjP0C18eX4fzP1iS1dFAm+095Hwir8yB+dUdBU6tcrt2JMYRiat+dhFjka5wakG814XzT4xfvdoMqbCzt4R5Hhl/uWZINjbg8E2TL4O7nS6KStuhyv2LOlHBAc2epbu3SFGBdSfYOw=,iv:yTrHwj0N6DAiix3PTleCVS+vTBerca/gnxHO4GTtEXE=,tag:3F/NV7SVkd5Tn8jkflJtQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
