apiVersion: ENC[AES256_GCM,data:r5A=,iv:z96QHUs9PxNXTlR6AbGSJBuFqYF5Upzhcy5AQYsnW+Y=,tag:HBARZKLjjZPP5H3LMmtqaQ==,type:str]
kind: ENC[AES256_GCM,data:VIfney3x,iv:jL+UydUTILEia+eebcfd4cMLfv/HARYNhm+3EQklORE=,tag:bQ7ZNAQZ6+UfzQnvDiSkFw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:qwKuKwl1drBbLK9XvPY=,iv:aqOgJwIbcrKQyZHAdBEC7HO8GWtjGZM8UXt9vqTbOkc=,tag:Yu9QVcD6rggXmE/2K16pfg==,type:str]
    namespace: ENC[AES256_GCM,data:E9Y0CXUXSNbQCA==,iv:G3eBH4DL0XuSW+k9Xmu6WdAa/XauLNgOcKwUDof6uGs=,tag:bC1DsQEh99B4kOJX5F5MOQ==,type:str]
type: ENC[AES256_GCM,data:OFgDMH/6,iv:uAKMw4upDGTrNfGaWLdhnP9YrAX08qMWv6Q+zxrfJTw=,tag:fWmH8MLYtwJzk7xtrQWolw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:NYnYjJpE9IrVAxlg1g==,iv:heumm3d0ln/6Gzk/NFXugx6H9QwyonNU4imop3TAKyg=,tag:D8iLSwBB774JY6HgCo5lEg==,type:str]
    password: ENC[AES256_GCM,data:cddOEiEujQ2lvnGzOYhfGefoIEqLAerSkIhrexmBaVVMjE/OVSjZabXO9cApFch503lPIryCksSHnUBj,iv:GmigiXOYjX1W8AQzrqKdKsrWU65HfX2aaeyjpNk6syg=,tag:8wEjq3EJNOxKxqIsYAhMpg==,type:str]
sops:
    age:
        - recipient: age1xr0zmjm2huqnqg7qmp6yzqdsf92aemxgvw8c8jy3zzuhty6jj94q98m0yl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1OWJTVU9GZlJVcUhzeUJj
            QWNqby9XZmgrU1lHeDhLWW1CcDVSQjB4WVRJCkpSOW41OGFBMnlOL1FvSytraklJ
            Zm5UZitRUXdJKzF0YXd5akhWQm9qa2MKLS0tIFVIQy9EaHZib2pjTEZmS0MwL2JB
            bXNTRXNaOXFEdzNlZE5mY2NyWkxvY0EK5kVu33GtLpxDYa5S+hnaqDryKzKzsk8O
            BN3SBRhJdr1Or1e3/5wI7drclO2RklDTVFXrxBXx4VkWZoicgPCGYg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T01:47:14Z"
    mac: ENC[AES256_GCM,data:2RpC/TwM99pmsD5yGcNQxEbA0B51xug1BM3ZqKfNEjvyh8h1oFMm2WDKAaDd/ay3xbf33fW29LhrBpXeEKYxiqOXOs2LbdDYENnLxnkURZmP7UKhJb6ZKHM00f8b+LtPmegV8Kicu7lrr0EtzTl2IGPzFQeaGGW2QYfQSmfC62U=,iv:Ox4c+w7t7TCBAdiErvbhs5PWGLCpNUhxyvV8/SsX9fw=,tag:PkCKnhIucy+I0w0taZfIIA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
