apiVersion: ENC[AES256_GCM,data:K9U=,iv:ogY5BrjknAsxceLLwtJxYrCC0bem8gN2COrty+ChVII=,tag:S7vzkXEBGPD65yW0NE0v3A==,type:str]
kind: ENC[AES256_GCM,data:PAXsEgrm,iv:a8HqT7xd6FK1e2ZRFJJ19CeMSV5/UxGvF112bkaMxBM=,tag:ZoS9iOTcpVqGg6fw8Gul0w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zPMmydwcLkISY61j21SQG/Cc,iv:MU5JlVb9sTiSYTTF5cLwOcfRaotjn5Y/Z79ugL8ko9Y=,tag:FDpAFA/ElUuO4mb7bmPY5g==,type:str]
    namespace: ENC[AES256_GCM,data:vKyWbjGBtzg18Q==,iv:dAn8l43ErOo6xWomxPJ4N8YePjykekpsWcrbhD/Uch0=,tag:qF/Dm9a7Yvfy5M7YcVrHVg==,type:str]
type: ENC[AES256_GCM,data:Jfq+Z2Nx,iv:KWLG8EIn7dTvnfcmMy00cZB23VDZ4gve3gwAU71+/fQ=,tag:Lxxcwv2Ce1Yoo0Gmy7Uciw==,type:str]
stringData:
    slack_api_url: ENC[AES256_GCM,data:28SSl1Hy+zLZT367hceQ8BGRBw3xoVyVTICn4GSqDJyemHqwP7y5zwhsi1qLsvLHDFgv954KqKCrN1eHbU9Jky2Jycm/C8anIx7dWvPj3JwU,iv:R1QwPgpM7XOsILCcG17GWDb6p+2L/6Y+ryGX2udZZ4s=,tag:BIVEONghU3hBHwtOx4yPiQ==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWit3SUVuMU5lU1ZYUmRm
            RmlFQXlETFhiTFBOcEpoVi85NlhNbVFvU1VNCk5pY290RkRPZEIxOG02VW5tZFRk
            bER4RUZnaFoxUlprdHlQTERkUnQ1VTQKLS0tIFJXSHVBYXdlMDU0MWo2TFozdHR6
            OEJyVm9jd2ZBeDlteUJjZFlVTFhxM0EKlbp0/5wI2yf4sL9wk5TTspxyL7K8/rB6
            S3dlixY5CpaIn4uafEs4Z1Izo8Dws3wXgPW+qztTeHzm3jVmv0mj8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T03:22:55Z"
    mac: ENC[AES256_GCM,data:LAzF4etA8hm6362b4kwljJyO4AFJthehx8cP1jxuDugREDqPBV869efRF6sdZjOH9OWlWqqwrBKFRjMVP2Mh2Kax0ALjMEngFVyEA2WNkT86+b4yR/MOyZK3/3BN7ISSmG/m4y+OI1OiqrvzxS/F1M+wOmqEkcqxtcIbmIp/Fcw=,iv:1Hlf7H+YsoyAnUZHYATvEtMrSWOzIFLibAAY/8SbgsM=,tag:udrT9EcsJpgZZIXRfDme0A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
