apiVersion: ENC[AES256_GCM,data:Oqo=,iv:4SyYUs9h7dVZ2VYChg0/YDBcagpDLBiUVxkbldxGHKw=,tag:J0qnluGdG2aqcXxaeyJPBw==,type:str]
kind: ENC[AES256_GCM,data:+hH+glMz,iv:a8JPrdSfVoDtM/grPw7Iwx3cR8OOhbnWHudt/2GpxNc=,tag:0+oMrp/J72hFr+RNoW8RoA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:vfMXNagkg6EvXwovvaeC3Z1B3w==,iv:uYRY/3JUcFRToQWyzPhRxmvVZsDjrOvs+ed87RWDHM4=,tag:+oPb6kL8v7qbCjrg9d9wOw==,type:str]
    namespace: ENC[AES256_GCM,data:lH9gvXFtTPR5Tg==,iv:GPmx+sIS603TM7J2ImB6AWAQSi1LluAm+MpPP7nILQY=,tag:zdqlzT/Aqvp1icvRfLXcuw==,type:str]
type: ENC[AES256_GCM,data:NhKjvIhw,iv:Tj7uJWlSS+lyoDozpxKccTtq27eAuVKgZfQrs5tjN/U=,tag:cizvprHVdE2lvSVXU3SyGg==,type:str]
stringData:
    alertmanager-configs.yaml: ENC[AES256_GCM,data:vBEpqlHcEgrmqyOIfZ1hwCfwOvRBD9YNTZe+21sfAs1uiqczLVoJ6ulCLsGjYHOnHQdi1rJfitj3zOUBcVcQFxsudPfI1H5JUeYrU8jSl+9n26XXmJ2lRdSJoUoXCbM00yXVTz056naOOUq855S3WGr9odSBfg+F4g9PfUfPKxE2kMiifF4zibvXMmtfS3/Fml6F4nOaE2vtnACJS6mOIt+iEYJ9WoneKkrv04Zl2IciMUvvJtFejkXladbAhHp1g9vvtmYnQL/xVAD5ccArTuM0Xr12nkbMahxPA45AkrdNiPb9ZJfA3C4/kQ==,iv:3ahIRuni4eti6fIVudZxtogVxQQkoz03O6tzBlPPJhY=,tag:J6z3vu7Nc3o7hs0OdQVW/g==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYMjdJaEtPaUpKVGlWWXdW
            UnNYeEo1aVR4cVI1NDltTzdEODEvT3BvV2hrCmRPZTB4M25ONmNsOGl5dDBaR0pJ
            Wm5UV1N3dXJkNFJwTjd3NnNBK0RnODgKLS0tIGoxaW4waHlOR1ErNldOT3NlSlZp
            UWNTTCt1NDV2OWJyYWVqVnc2T1RFOXMKB3N3Ye8PLpyEukrRegZ/FhnsIgw3q2Yp
            vzxSpTkN4tFkbs2fI97CUBJjyV2HlQboGZ0IDQXF4TuDQRGKb/P0VQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T03:23:00Z"
    mac: ENC[AES256_GCM,data:Q73NHEsOgODQiM7eABMuJO9f4YHCpmz+M839hAQKsx8g2VeieVkiJqxEnkMXxrzMTCKD/U751CbCaivkEyyKTxjYemewqBbLmnwHjcPe0+5rbWkSNXk1AdSFgvoOohaCHT5HEYuJBS966U4DkMR/HUo4cdYT6z7hoYFpSbI9xvU=,iv:eym/EDXLPWd5QFxhunTRJDupgbVwajgmXznVQIP/6mQ=,tag:tDoeFuWWNtE3XRPUXRqMAw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
