apiVersion: ENC[AES256_GCM,data:Npw=,iv:zg9vDsb9oREczr+Mw+4AzW2YQRDoYKJWG0xgvRgY0Jo=,tag:xnwTSgPQZbJt98t3I7upcQ==,type:str]
kind: ENC[AES256_GCM,data:JJc9sW1F,iv:4sD9NrDOV/Mdt7sGtkvG3Aox2ThGNQYxeFY/hGxuTeo=,tag:zixpuKR9OWBwC5JsS5S9/g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:r5tBAipWTtD0Wtv3kNqgc7zHiM/R,iv:xwhi0hc3d9haYJhkJie/wLIqe7SF9jK+SuW3kOxkn94=,tag:6FDTUbrgFx5ltt3M+NVnTQ==,type:str]
    namespace: ENC[AES256_GCM,data:LEuZ4ItfVqQ=,iv:DEQEP/37bEvWjrMrRUdQo3t50lELX+kRulbR2OyE5jA=,tag:zwLkY78L8WjSNiAALWf3nA==,type:str]
type: ENC[AES256_GCM,data:btnGp0bM,iv:vMn6/e2m0YwMB/kjXM3aPMJ3Bcpcyc5QxxU1zIYo/nw=,tag:zlvQrtQMfE/dQoNQBf5Gcw==,type:str]
stringData:
    password: ENC[AES256_GCM,data:QxU5Pulvl9jDRXOj2pI/PBM+Ii/Zh1fgwc4MCIFLGIERNisbBOuNeA==,iv:HMr8Y+Yno3YL/ho+pdxkTxPj8hpLW/bAViwsUbqR7BU=,tag:kWJiFWm+/5aEyKDXNQqM7g==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia1I5WEE4d0dwRTVZVjBS
            UjBtR0loZXNLUCt2YSs4NFRqd29DZlZyMVdnCnBoTzFKcFhReEZ6NGNJZkFYc0k2
            SklFSTNudkNXSUtYeW9nK3QyK3hkTHcKLS0tIGMrcTdOVGRhMTdwcWg3L29qU0Nr
            eG96c1VjTXRpeFZNWjhRcytKK0Q0RncKD01WECJcYlEVJV24Lunm26Ux0gSAyNwq
            uuvJrUBSqtPY2R05cIQx7U5qx5kqfWIndcc8hSUYEdKUw4eKSPhffg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T03:23:55Z"
    mac: ENC[AES256_GCM,data:bF89qp6Dx74fpyg59+jpScEJF9B0KKY69ceDELiW3eSMeb/UP4RpE6zABNY0OYs6H/4VTDqqSb+7y8AX5Q2Hno/gbJCBC8Fv3Yc/bIp/Y/7ahfgh+J/iwBbHWi3ut/SUEQoItK3Vf9O6wJ4Zt8fI+sOBF9auCS5BiG/mLoWomxI=,iv:993MOQK8C1MUliqayTugt5tPYt5BeIwfkgtucVYPdzY=,tag:/9MuPnDTBAAr51UXZBHSnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
