apiVersion: ENC[AES256_GCM,data:s0U=,iv:xeYbV1ic4LTBYwpKVk17kFCOKEThxryiD+MFIy2Dfl8=,tag:sTKlrm96q8VAT7hQFYN0rQ==,type:str]
kind: ENC[AES256_GCM,data:TrV/6+5W,iv:k6dfOgSQF+UAXbeJ5qY9bHdEsj0pXdYku+swTitdcwI=,tag:9QHhaZ86KIhCCHV2Fq9yNA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:W7x4RV5O1vUHtzQDXcW0HbyL5Nk=,iv:FrvdaXQd849jUbUmBDt2vmbRZv6RoEdLfILkovoIGqU=,tag:YRTBJUXCvjEaChzFNKu+Tg==,type:str]
    namespace: ENC[AES256_GCM,data:rem+38dy9WE=,iv:7EecS1JcwwLwyq/Rtn0GrrC413M8Jdf1mx7ktkseC9Q=,tag:8kekMYNfg1qw86zL+HkkQw==,type:str]
type: ENC[AES256_GCM,data:y4AGjmfl,iv:mVqF3u69kAeHluXOn7k3bOJy3KClwDbd9aSIbaksuj8=,tag:BRZn7eQoErx02kooHkyeLQ==,type:str]
stringData:
    password: ENC[AES256_GCM,data:LYf24DmpCygiWI7TS7b1sMvxug==,iv:szwW1CaizZf6s2l1UpXVJPRqr1J5ODcX5DOer/l0wHA=,tag:MBsX8kkIcRpMUIAD1S+YGA==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwc0svbWFOa01xVWxLcm9E
            OWJuT1hLRjdkb2c2dTVWWHZkNkpwd2trREVnCkw5UUl6ZENJNXR4SFdjYmhrZjg4
            aTdkeUFsbjVYbE9NaHJpeEZ2MlBCQ1kKLS0tIFRaZUxEMGRuWFBBWXlLbUd1RmVM
            dWNJM3JSK0FMWnRQYUQwd3I0Y1dVTTgK0fSHat+kdCc+8hG6NW9zH80FhLswkdHv
            XFQHepRfPjU79jkAq3k7bpHoDePh8CwskNqFvyjd8xuMQCoC/Puvnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T15:59:08Z"
    mac: ENC[AES256_GCM,data:m2iHQnzlPF7/pO89+dojMO8rouBdSd72sVycgn8/b5ueFFhLX9MAItmZ/xftv2Q84qNJLlfK1E4JTTsq3eLBR2kDrCNK/Qi00OuIG7A3KNOMU2d7U8yYu53injKr+hkSr+e82yuuaCchAZQ0iax8ZndXiBS/A+nBR+D5XWz6fhk=,iv:hGahWUB/FiNxxnPJhHeCO13HiB0pddo9HBF7KYPkNHs=,tag:dj3AGd2ApiH+mFjtSFkDvA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
