apiVersion: ENC[AES256_GCM,data:J8w=,iv:XSmOyg8+QvA5sYKMRgFekddWa9qt64d3AstYlJAvikE=,tag:HkK+ugu2PkN3yp4FpvLgcQ==,type:str]
kind: ENC[AES256_GCM,data:27Zus7Sj,iv:qErd3DTCLP0qH6VZ6Adprezut3jANy50K5VATdoz6H4=,tag:XCIH2ykw3Co3If0y6caglw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kHypaqilGJHoiWq+hXnvBJEfK6UAXg9ubqGJ,iv:AAZt+IBC885rhNwEFdbkFk0HMFmKyNB7Rys1p4+MwjM=,tag:dxiOCsEXL5kKr0Z0u9ONiQ==,type:str]
    namespace: ENC[AES256_GCM,data:RWypvNIE8xA=,iv:u/dugbjifudZ7Ws2Efk5N3tKHDjnnGNhVC54Hn6VAdg=,tag:OrD0NVCh4zaXsz13DWewEg==,type:str]
type: ENC[AES256_GCM,data:gd1xKWAK,iv:2djB4ClHaLzvEK+BHZQPKkZAqh5tsv/5wEF4Nsdlnts=,tag:2apQd0LVzelORjFTewMHRQ==,type:str]
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:MpiGGuHMAnw/DLJRXop+Di8LI2Y=,iv:uxtVcgMYH2CeVY5hkAcuwZpamfYXuUMgJbb8ZOKtuVk=,tag:D/Noa22PUP0MMWiSa9QtkQ==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:rTBI2iXZUlfHdOOggEOybZoYlwpkEZY16XOjQW3e9ViE4Hxatz0zoQ==,iv:km+7c1ygwhHGUDgiIDNydTLQVMw84cF1IDF6sTjvev8=,tag:6X/nO/y+LWpilzGsYgE72g==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVHcxeTNJZ3V6RUVyc2h6
            R2h6ODRYVlZnU1IwaWdxMWtxYzlmSWxmQkEwCjluS1FhK3NUQ3dFeUxxVWFXUUdJ
            MFJXVkpvNnRiNmJORFNTdWRhMEFSSjQKLS0tIGpJTnhKSU9oNDg0ZjlLcTVyUm5C
            ZkVjMXVlcFc5aG5HS2xkT0tYYnNMbUUK1kCkJiGn0nfB56ZvDUTJfn1xd7y1wCcA
            EPc1ULa35oFlNaksFiV90gOucqqUwR909wuovcEg1IaIC//JO8kc4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-22T19:03:20Z"
    mac: ENC[AES256_GCM,data:vwsVggwL7RRHQsbcWsKh5c5dweybKP704OARE5ZaB+KXTOwbfn/GDF4tfZbD/3VNdvsgFJ+Fc7BoXhtarK7JFHc1lABsJj+Be33DLSQ5Ep6bt1KmCHeeA+sXzsi1whPLme27VJ5vuumUB030zcTEqGjz0JYnupSfcd8Yew3uSvQ=,iv:+sKGVi4cKl9vfDBxUXEEGR/Qv3dxf3wv29S5FitPliM=,tag:GN5J/mPAmd89HD8deQIELg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
