apiVersion: ENC[AES256_GCM,data:r74=,iv:zNTsiMEAHo0FQXXiEwjOlNLxG0kDWShysvEcNrv1UyY=,tag:GCviqw6EDFKRoTlOpnwXjw==,type:str]
kind: ENC[AES256_GCM,data:+N5bjtSa,iv:wW8KxvwBzRnhjrooPeOiQWJsMyXUtOHuGsMipXWGvYU=,tag:FDBpsRft1K46wDon4to6HQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:xjqS2QbrWFIP4hHacMzOOgLT7sQ=,iv:Nb6kcQysdMTwqZ5hgAoAhhW5J+Aim2TreJzb+uo/GV0=,tag:J7jSwkRLmf2pBmUdxaZ0Rw==,type:str]
    namespace: ENC[AES256_GCM,data:Zw/VwPG51KU=,iv:JEXNm/EQVwJ/aXyoY9gpVQe7mp2sL7elKnJqMy4Hvno=,tag:pCNaZv1/QnPgGRJXbk/Zew==,type:str]
type: ENC[AES256_GCM,data:Bjs62pJE,iv:5Z3V6EqZT5DMtS6hSpFPlKxQMM1R9Q+YMDg4Wtp0N90=,tag:NnSdArg64ygz2+ZFhASQXg==,type:str]
stringData:
    password: ENC[AES256_GCM,data:GMTgWsL7M9OWxQ5V2p0UF7KRIuLwZvHzrEe0d2mNfg==,iv:brDkPCtutSJrhU1Anj7NdFa1hhVA3l0t4M9EXyAaAuo=,tag:+NYn5Lh9mbLjm1PgTI/Dtg==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDUFAzSkk1Yk1adG9tRkY4
            NkxOcE5veHRvUTZKV2FiVFBQcVZJL2IxTDFJCkpvSmRmSXVJNVBETUM3NWRRYStz
            U2tmSGIvY0RIMmNzbWZwRmdXUDM3RWcKLS0tIGdSaDg0NlloNm10REJvejF6b1c0
            bjNpZlN5MmR0NzM0eit5RE5selFvcTgKiQhO+yFzekmBlxDnrEne1bNTj1Txv4ct
            Gs6Hxjw36WGvccUriDs6C0Q7rZnlWVBxGLPD1FzcOLO+p3D6BCoB3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T15:53:50Z"
    mac: ENC[AES256_GCM,data:W6izYKAPIpXLAT7pRws2h6EXPk7lLhUBoqb1H8iv5ET3PSWV9p5cmPrwdOUplPdicFGMbGN6GBc+cYKwMIztdFGdLwd4DxXowXMEeEbXkqA8FDLcbE4dauMEa8KMC3N/sOl74UIICHbNgSQWdfi/rpAI9+KaajudkGxiqj+X1WA=,iv:mFtK8PdB2vnB+C0+3MBth7QT8XPnvE8YIa3VFBeZshc=,tag:KZJtLoLNrHJcTwY/Vi+7OA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
