apiVersion: ENC[AES256_GCM,data:Gmo=,iv:Hj/MS9/rJEVVaBvYYI+E949ArWkcOkDRJnmLdU9EeLs=,tag:0vZgfoCbJZKgJR9JjCOVIg==,type:str]
kind: ENC[AES256_GCM,data:LKBgT1R6,iv:ZmxPeAPSPBCv+PvHjwVw3EvCKJe/gFV/w/ImkFANrfw=,tag:36Lw5a5X9ehnmVU3+jdm/g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:7WZjzM/icKnIWDyGWPNoVbucOw==,iv:XO/zhywjyNEt8Kme653/pswyk28Lyn3A0pBhAraiooM=,tag:nqAdlc+j2XjwiLevDFeyBg==,type:str]
    namespace: ENC[AES256_GCM,data:EgI8m42s8/gPqw==,iv:jAlWsqb/Uz8OEHHSHZk7n6o6jgtg+3MWo585qe3+2dA=,tag:13OlSOb7LPEw6w08yIEXYA==,type:str]
type: ENC[AES256_GCM,data:KpVqzw5b,iv:oHWDe7WjGJr78BEjTz+QEagqo3o+ayYxN5ShhoXv4iw=,tag:uJqwjoLtHsb1S/DLk5I4CQ==,type:str]
stringData:
    clientSecret: ENC[AES256_GCM,data:41U7MTd9P6TMe2lBpEJaL+7772ZcXWb+QDuzaTh9Rs/ipAWAECTYDkcz5ugBb1Z4,iv:xo36xWq/nX0TzRcwXiL/PoizJnoUjZrdQyD9pQ3OOOI=,tag:4BdLF8nq9Y9+eZSwCHLY3A==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLRGE0S2p6TzNVQ0RCUklw
            MFJSSGlDRDVaQlV0TGtaVS9lb3JJRUphYkNzCllUSG5wdjBZMnN1QUgrVko3VEF0
            N3g1WTYyWlNscmRHZ1ZiZURNVExDajQKLS0tIC9VWTdQUnUyR1ZGbXFJWEl1bWc5
            WkNEbG1ScC91SmZPMXdJenRHTzN5NVUKhHEGrw3bfyBiCjAho6Zqomiq+ZbKjVLD
            vVXOXPTWnqZFPalS5JwtKcVQie8K5yyAcPjjz/gHpOv/W3QywxhenQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T22:28:10Z"
    mac: ENC[AES256_GCM,data:N8e9xpahXTkzE1/2EaeQa1vgbwuykJwTZmn3Yw/ZARr1p9ctIaorQmqCiDsuyEPOOIt6WGFgi6T0vmJJ6kOIDLiGn5nRmfcnWHK3euOzhcVEr/5/wUM4YriAsCPmdGl2GgtsTJakZjpyaEG2yBrBzIW5GuvcrNVq0aKPh66H9CQ=,iv:H/ZNjnSBlODPXySfx8kKvp9C9J1W7A3DmtK2LsfaiFo=,tag:GoQx7C+izbXzN/sGiE8sTw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
