apiVersion: ENC[AES256_GCM,data:nN4=,iv:OI2mq1MI0gXVoIBrjy64z1Sc2LbAkP/yFOorvHkrnzY=,tag:ieRqRGvln+q8dyPOwNGlaQ==,type:str]
kind: ENC[AES256_GCM,data:UHN6Q9Vs,iv:cYAEZCe0MjLY3Phqm2LlkOFQWK4rccw3pguCkj1y8KI=,tag:LpQfad/vQ0xrF3RcIgkNJA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:L75gvGBzEsaipvhpSUjFQXXod/IbQDWHzpPI5A==,iv:4xFRcRVco8bSm9s60jjveUaM20wPb6JpZ8YJJPhRPyA=,tag:svJOdoKDzDLmdhxzvTTsCA==,type:str]
    namespace: ENC[AES256_GCM,data:5MvqvmsJmB3mmg2v2wE=,iv:z1ZbbFH7MMEDP9yZM4I9IN21qqKLpdHs2PiMJCZccmE=,tag:f3NWgqgb1GSGOpJhMWqz3A==,type:str]
type: ENC[AES256_GCM,data:iKnH5Q2T,iv:5a1fN3trKsjccnMPPrwjAPPB32pXgsRrWobDJrxXRFI=,tag:IxImB46SEn6LemGPrfVL1A==,type:str]
stringData:
    accessKey: ENC[AES256_GCM,data:lWWzwiEj50OMSm1Vx05gpm4meVA=,iv:AejCem/R2CMaEByLXuzHmc4bXzIpffyhd3i7T5BMROk=,tag:RWHjeSW02EM/umeEfNS1IA==,type:str]
    secretKey: ENC[AES256_GCM,data:C0TT1X3UV97MLITMLqnv0+aAEVBjJlI/YhA+Jx0Pb2VbM0yaRf2bjA==,iv:p/PaIalSD5JPFso29ZWCb0ttUwSaKybK6/CUQgrk0fM=,tag:g67bO9ym9JHHVK9iJtAfoQ==,type:str]
    encrKey: ENC[AES256_GCM,data:HtidPF1lzYEQICQ+N7zt+h4cgyEZ7DZQLrgNt8WE58NHyJs63tC+XEKVXbY=,iv:KOyburjt/hnCh7JkR3aPbsjEnkNbKHmzuxhuyRpABUA=,tag:qBgYRLckDS/0wcm+d4lokA==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHRmMyakF0UkFJN2NNS1VQ
            TnZFeTJhSEwyeE1uSEVaeTlIcGhBY1RlaDNZClVQMjhrSzR2dVVhcnBnME1LUHNw
            eHYxOUNHbVZrVHJEbk5tK1JLcC8rMjQKLS0tIHd6TEpmelNCOG5BVk90QVRrcXpI
            T29rdno2OHo5bjZEaVowbWxjZks1R1kKwFPPQLFj98lz4ghNXJeQHB2uU68bQ3Ek
            voy7RTXodqxm0qZeVaEhMTmaLP3uYkGsxvrGgjxbKkBIpV2OEnJGRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T21:11:13Z"
    mac: ENC[AES256_GCM,data:szaiB7whnCAox+TKI3wezsKszxzVRhVdBL7jXzd+FRbTHTsjtxOEo1UU6ZZ6Zq8+g/ygodbnizvmECXtEBJElOiIGa81MlPf71gZbOGyiFswhs+uBp/2ZLhFO+yZYFSD6TUXFg4SFUsoeeqPP7jQn2j1OShNNYNgNVRS0kJX/FE=,iv:fht4z4c8DIPlGuinzM/KT9V5YS4x1KMxkYVdR4fK0KY=,tag:dlf64W3BiFR6R7PmiUkJdg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
