apiVersion: ENC[AES256_GCM,data:+qE=,iv:qd3XR2KyCVdY0LpOzYM+AAmIGTr6fpNoM9tV+/YQUGs=,tag:Ks3pz+hEeO3bUdmqHrUOzg==,type:str]
kind: ENC[AES256_GCM,data:xapcqYmb,iv:CaO94TYGLwAucDsH6KvdwVeTjcFYRj+kdVU89Q3pGb4=,tag:EZAatddR0b8ogubwtsB1QQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+HoM4S2n4pdYZo4g+sll6lg+OX232oO3,iv:hHm0BlpTjzVhF11YptI/dIoSzPmt6Zg5jBjjPnZW2Do=,tag:ZK2OzEvxFlsMs9JliW2ZxQ==,type:str]
    namespace: ENC[AES256_GCM,data:y7zieHvl4vJlpn42z3M=,iv:g/8zK+4LPU0id8OT3uEelZUVlga9URuddrzpNUVWxmI=,tag:shtPPlIuq2NHtsh83hSbXA==,type:str]
type: ENC[AES256_GCM,data:/OOi0hib,iv:Qvp/dxI1XyCayQ1gxqHYjROseWLoncYREdW4hJFoy3A=,tag:ute5gyCCqqjIJnxa3iN22g==,type:str]
stringData:
    password: ENC[AES256_GCM,data:ignrTl0lcHsNNFyIX3kSPom2bw==,iv:O75zROoCJSZyQJkHmahdgB32i9aXUXfJfv1ulcpJ+eA=,tag:rpnVo5Ztj+4ik+tsXYaiKw==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0N0E4K1hRc1BveHBOSUE4
            dmk1d0ttU29VNEM5QllFKzJHNTYyM0JjUmlJClB4cU9Wc0JCS1U5bkpPSlViY1ZX
            NlYvZzZHMWxQR3BZVEJpZVVzY3FGVE0KLS0tIFZTYlhNNldQclo0WGUvYXF6cDk3
            OFBtaU5TZzUwMWJ3VHFvYWVJSndLZm8KDxb+XjzO6+d4ALPRZDgw3KAp4zdAj/Wk
            SJdHnapLlu2A9cFyLtXOIZ0z+laW7wkLOgHapy7MlfgNkfz2+SmJxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-27T01:59:20Z"
    mac: ENC[AES256_GCM,data:GFY1voVrOeOkABCO4BXZkNhdfs5KtK3am0OkGrn+U9hstuTrMQl1HdWPO3QjYfjUI/w09r5q0VPkRu8UPMO50IFAF7wWR7dZnoT44quopv6KV/yZDi7t38STk/6ZP4o086ms7FZK9lVKYO2qcpWuAEfwp/Kazz1wMbdYXfoT5I0=,iv:gq1/GSaviPgssgTER+2Rd9uCJXob8aAP2905bknpn8g=,tag:KkrgYj3lQMxMZMbT2Ds0Ww==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
