apiVersion: ENC[AES256_GCM,data:zh4=,iv:s3ecdqHKW1rG+4mD1wRByMXziQ9F0TnOfYjHtqfYaC4=,tag:fusUgGSSwhQFAoPh73Ej1g==,type:str]
kind: ENC[AES256_GCM,data:FEhhRzaw,iv:p1ZUzV6qox4/M6tjO1Z+FnZ4N98+C5l87CBCtBeGFfI=,tag:nFb/LP8k82i3U4JeyKmOtw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/5MTLo06C189QuVbtQ4=,iv:K8DVXB3+IJZQBxhxs39kjAX9zilqaYNCdusyf5WxLUc=,tag:MTwHotn3PolUFLlPlLzNmQ==,type:str]
    namespace: ENC[AES256_GCM,data:0DmMfXxDTg==,iv:PCtp7VxCqgGF1hBN0SLg7WHh6uVlnahN4YKBaFH7Tfg=,tag:tDT8ED/w1fvaDveVohh9Sw==,type:str]
type: ENC[AES256_GCM,data:Rbi9vzQC,iv:w+6pqz6862qzKrDhMopBmf+a4MNBvmsuXOp5ybM2xlg=,tag:n9R0kjSa6OHWcntvZoP+mg==,type:str]
stringData:
    ANTHROPIC_API_KEY: ENC[AES256_GCM,data:KM1bnQJ018xKpPHV5DIiYRtI1gNI08GD1uFuQZP4d6KTRdko9f9HnPwsRa85S0oHl/2fZWsxWSdggO37v7ZE7PlZwgzrpnwHvNj0hZ2IZQiTh2ELRtW0S5yLYxryklZq24kDK7p21n4T1loO,iv:GG+jiTcEaWUlEr3KREFFCElRGgcrLeIoiKCk4YwHrk8=,tag:QRlhdNOTbFV13Mw/vGl/OA==,type:str]
    LITELLM_MASTER_KEY: ENC[AES256_GCM,data:Inl3xlSYCdODVqYCm2WWvi5QpeWyzGDa5fLNE3Xvnr9Cicf1gQN+etI=,iv:fdSkk5GOqQNGp2QqeeE9Wh2tog1Y7RabQRpLOpYU95c=,tag:azr/PtD3t6RC2k6uXZvhHQ==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNHZYRWtmYVV4U0UxZGhZ
            ZWlNU1hwMGx4SUFabnVTbExkeXJ1RnRELzN3CmtCdnRVZTNoNjJIazZrUVNyenRl
            S2QrVWF5aThQNHlVYkYzVmluTmFtNWcKLS0tIHo4cDZrYTZ4OEpHb0x3c0EvK1l3
            eWZFTVI2S2tyY3pYUHQvMlJpOFB2b00K+NYq+NCjFR6KpDbpEJ2Q/tyfW1w7n+/s
            +AyM/SgFbHwQXHQ9UB3UULunzXfEbK6vVxqeIXuHefFCqNNCSAzMiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-15T21:07:03Z"
    mac: ENC[AES256_GCM,data:tZIdM2Z2unWwTbwimkG+GY5jrtCtGdtak5g8+CYOpM2QufIHuq8itSN95zytb4j8M2rR4IAUk2qcLUbZn8egCivkamVRLOm8K+zfQDRV8fuWyn1Bn+dNMBPq139dr3UgxXWjB7L5AIKtahtd/mV4VObXuEAZlVCBpZP8zK/duGo=,iv:7Ta9yWbkmRm9gagqBFim2Ch6MHFlCAp4Z48owEJtk0o=,tag:n3jNQfz8sbaUuexyyuGANQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
