apiVersion: ENC[AES256_GCM,data:ONs=,iv:lQhliluuCYtuHHRiCjmGGn1RGo7G0UTYGg3OckuzzGg=,tag:YiiTlJXsIfaZWILMs7HFqw==,type:str]
kind: ENC[AES256_GCM,data:8D7M85Ru,iv:fTBJVwrrk+LnEAmDx7gJ/EIqO/I5RrDiBqCJzBroHIg=,tag:LxUBaQjavX5cTbu8+/+yzA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:y5V/RBrtBNNe3E1W,iv:sMawXlKx36VSMvwOcTIHny0wAIJNp+gNmh33MFhzCWo=,tag:Wl1v2ry6JenomO/5zGAVgQ==,type:str]
    namespace: ENC[AES256_GCM,data:WuAdvbmsf/k=,iv:39LSKH5Z5cTm4xuquaSTdoge7pk3vuu4pMefpuiPFQI=,tag:jzFZ9g+7Srh/y4w/4yPWWQ==,type:str]
type: ENC[AES256_GCM,data:gEERmcBJ,iv:DpP7HvmpHHk5dC9KsooIYMhEBHacrTa8Tkqglhy6Ais=,tag:O2BlMSfjsdUxz0jVSfb+vw==,type:str]
stringData:
    jwt_secret: ENC[AES256_GCM,data:ah+7cIGtuMXhPEoxd9Ovs9RR9n7sjRXX/jc0fejkm+P581tQwARbSj9t8ChGBkZF,iv:lXedkrZGQN/Yt2lYvJP1lPM7Bzs0KdUMIdm+HncSqG4=,tag:ikmwfvoW/LCQoqs5VAqNwQ==,type:str]
    key_seed: ENC[AES256_GCM,data:aDQHYRpFTlqqW2VcwnsFGi1bGNE2mpG7Qq33VF1/rbR9z+msjl84bQXtIo32IWkU,iv:KzHXeLzg15Qwe/yaFzIbyufMLPXwUqoC3KdYb++ZmWc=,tag:0mLhl7uRPJqK/XQBkvcbeg==,type:str]
    admin_password: ENC[AES256_GCM,data:7wvxBbiH88Dc1Uo3GV4lY38KZ4I1GaLk,iv:wdXws4Os05MKDwObi6jfp06hUZhUNJRyJ76Crg67Xyw=,tag:GIPcVZdGMm/4n0+y3W30pQ==,type:str]
    admin_email: ENC[AES256_GCM,data:k7o+wpQNEPe8hcoOHi8jWw==,iv:QZwovL1ygj+TxPE/9SWaSVgCxxjDBoDBQxfdvcMrJUw=,tag:7qOEf+8aaGlX2O6aUOvQCQ==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSWxibFg0SjV3SDEreGpk
            eDJsQjBHTnFkcm1uQXlMTXZlaWZtblBUaHpNClZXaVpBVVpnanIwcEFTbWxBRTl6
            Q3Vmclc5Q1VldE5ZZVJQOTVPT0VWNFkKLS0tIGVFbExJSVhLQzZwclE1VEJTU3VT
            SjBMUjNTUzg1c1NKN2tmNElFNUVnYTQKbEEGscbzuc0xZGt9uQxs0AOSZSE7JGqO
            /hbbE5QlriaitVWQtrdMVe5TlUMELu2YW6fNrfaPDMsr2tzxqmK3Fg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T16:06:48Z"
    mac: ENC[AES256_GCM,data:tt8utSDaSOLmICsHZf09zSdF7FGnlB0TJ4RydARbEzKn77tRFTPc+vkJ9O46PEr1r2oSd7xhPC2DApwpX2SAKR4DggDByJdIm5pgGaI5SBEOEut45jq1HtOqTd36qJE1jyXsXw69gWd0ZAEsSkboGOstnAEs4p7MPxRi/BQddSY=,iv:HzL5yCNim6nMClAXlG6Mlz3uGhKBXZBiV/3Z1Ytotvk=,tag:0QqU9kdzrCX+3HJe1yTxTA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
