apiVersion: ENC[AES256_GCM,data:2oI=,iv:acj4Sh8Vwb2TFa8XImkQpwpx6L8eqXFHbq/NSk6NLvc=,tag:dndRGyrVVBnLndLMLZf1cw==,type:str]
kind: ENC[AES256_GCM,data:XTq6Uz+r,iv:NCic2v9zXNJDfS1XIRXKGJpWuG1sJashfKl9CuZr1RQ=,tag:b9aDEzjeH2yvnQ3SBPlKdQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BjwyAJeItMMvOhJaD7u8/WXyQ3wn5itp,iv:siQp92Se3x0zG3h17mqBGQo9tDWapVzmbIiBl+JBDfs=,tag:DnmLgsxk5kducC92PVUnzA==,type:str]
    namespace: ENC[AES256_GCM,data:J2GprkwV/Uo=,iv:URX8yKH3NPvmibAb3I3wbUDKbKRgO/b3lHZw6Y2tSFQ=,tag:9wv9KQ0BT8z9byCVFcUDUA==,type:str]
type: ENC[AES256_GCM,data:92Ny2Zg8,iv:bNeIIFZur27bGd4EFXfKyqJ72fU+/ozl/jQqdo8p8MY=,tag:NUPdzU1UvyNXfZnYoJaPpA==,type:str]
stringData:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:ApWUuKR4zv0cu/qUhcV+Qzp721Y=,iv:BbBnPWUXCSABoSkejptdI7YvSjKh8M8hoBX5+VbO9ec=,tag:qC0PWfr76Od/RdqOAx52gg==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:Y1t/qZoy86/9nGByHDiopKnYzF2iVRWgkTESqH8uZgY6dr5nPs9hHQ==,iv:+ANp56i6Z4hNo9NRvrr6uc3CU/gsTHhLLOw42+Xyqcg=,tag:llz8SzM0v3kGljZJwAGPnA==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYkorK3drMG1WdW9iK0dy
            SFo3NW1FMkdnaTA2ZzAvd3BmTWtRdnEvQUg0CkxkL2lMMGsvTWp0RHpNZVZ5MjQ0
            THBERzJQZUdWN25nSjJkSnNIOXkyZ2MKLS0tIHlsRWxFYUs4REZwSHAxLzl2eWE4
            L25mWUpUNWs5WUlDaXZNZ3ltUE0zbnMKsv2tprl7O83RQG+Vn1BKrMjtobgy6T+O
            U4AgaedLYULRI1t4QLFoft8Wb7cWZA93deE8b6Y7yaeVbbvPywcqyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-22T19:04:17Z"
    mac: ENC[AES256_GCM,data:YPUwo3a3SsXsuuHY9BWu4v4D9NLyJRdOXB4f9aeg4/XkrATTvcn5ZeyO6GA8vfJNpTPT7USiwFG2bImH8wDPFjJnFGrfkf19DdYFzWt4WKj+GB/zJFn0HP3ilnmzLTymX2oZXAySyKp7F8LVIJmRTMiO9/kibRvvtUWYaoD3Q2s=,iv:m0LvtMgVoG7+9z7AFKW+/cQffkPElsCk211pQLuArSs=,tag:/UoDjTfk0Jncd2ye36Ytfg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
