apiVersion: ENC[AES256_GCM,data:DTE=,iv:E9XgH9gRg8LMJMsQUiDAAIjWgvfaEYQpyTA93RbIgHE=,tag:dQP3q2XZTMBYR+rvM+r/sw==,type:str]
kind: ENC[AES256_GCM,data:JFdKPqxY,iv:AR9slXHVvMP+5j2cGse9uSoTUHTx1PXlzy455Wmz0pI=,tag:pKqaHYVmze/ThgDOUh6vCw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:+Z8G3oFG/271TZ3j,iv:fx54irngRJ/U4G6Qx/xS8zh9nN8KPGO5dfmogBeiX8U=,tag:uMW6Y5YzcdMrGJYIhvuO4Q==,type:str]
    namespace: ENC[AES256_GCM,data:BzEIsSnpYWQ=,iv:Gvoz5YDSONXjhc3OTV4BIqLNN72iUBbpIV8eSTRR4iU=,tag:2qJ6/5n5uQSyXRnpht/StA==,type:str]
type: ENC[AES256_GCM,data:xjRNrUyt,iv:KxAvyCUe6iyKUcGjnqKBXW/EXIWSJfKcQ4xcqWAPUes=,tag:kRzg4zMV0c9JZOKz7GMB6g==,type:str]
stringData:
    jwt_secret: ENC[AES256_GCM,data:iT4b5Z5bV1OEMXr5fuv74ulNMGv+XbRBUqEmkPd42GjXL09XEiMVvhiAjbl0fjET,iv:2qjr+/Bv8+2SbHaxRamP8UP3AX6hLHeNQlY75WXpVRU=,tag:0GlxuORz9W8cpTYMbUSJRg==,type:str]
    key_seed: ENC[AES256_GCM,data:Xfo6K8cgXGznPSTHeVYR5sWrENGPmibSlfn+bBwQO2paozsbEBpZ1BJ6Igea0pTe,iv:z7qrGITh7B4/WU5MR9NNeaoUf7omGJN0kDIfja9xLtg=,tag:7Xtr5eDK9jHJKfdR3IxGtg==,type:str]
    admin_password: ENC[AES256_GCM,data:sPOML7kpNFo7e7vSKPVFSDyV+aK3QCbI,iv:bQ3saQbWWw8o7GAkeX3uU+pSgdDN83w+kBhYisS1gzE=,tag:c0LGxqz74kie0dRkIj3uRw==,type:str]
    admin_email: ENC[AES256_GCM,data:6FD6FlAetYvq1/p+9I1oruiP,iv:cEsT6jAllQ3usbX7v8EVM9n8tx56vp3hSsq1xKuabaI=,tag:I9AaVuYW0DY7xBwuNxAf6A==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMDFoYjg5Nlp3SzVVMVFr
            T1RJNXgySkF5QzE5eTBuQUtJaEZ3RDJNK0JBCmdkTlBobGZJNFNoNFNmYkxJcnpM
            YXZEREQ5S0d5Y1ZGcHUzay9VaEloZmMKLS0tIG41ZFUvNHVCR21uTEVFalRZSGFS
            OWhmRzZtUC9OcTUyeHV3cUQwK29oQlkKPP4nQV9c7MzbjAPmernSWjcOC3dFKx9b
            jYbHisBHqx7t4pvx64evgvUNQmhgDTT21VlRf8Gl6GaZcnuf6X4frw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-19T15:53:50Z"
    mac: ENC[AES256_GCM,data:SZVfQyrGczMoJClQ/QuBAkpOLR7nV0lynrmHparlEJI1ZZkpb6iumLScNKbZAWx+OACeh/AObqvpMlpWY0onGqnx+0s8339v4Z3CMqqrQeJX9wN24iXkGji84/yorDH7+Z1aMctpXU8GQuqzmQcHm8+3tnOKRpszK5g3/MmNDCI=,iv:sFj5QqkWyzTOBm7nVOSoXR+Bpv9La0gZILMZ1qIMxaY=,tag:/HC7ShAk3OTiAAmNPRcdhw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
