apiVersion: ENC[AES256_GCM,data:aFk=,iv:Q/vwVXKpCht5jVGMFYuQttLxVANDk3OJswRzaY2Ucrk=,tag:EZfTTpil9fsNMcmIFUiZoQ==,type:str]
kind: ENC[AES256_GCM,data:ZxDT9Eo0,iv:6pJXfL3D4LqoaVurrT68s0J0QALPK1WCHZsL8ty61Tg=,tag:S3abH7KDcO29DPSLpM8jww==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nCl7/B/ibAP6utupAu9Y2w==,iv:c+KLmp4q/YPaNVWfiDhy7w4s12DdebgSoSL1XTDjDtU=,tag:Sddm2e0xI0RNmqb/58brHQ==,type:str]
    namespace: ENC[AES256_GCM,data:U271N6t8,iv:u9ta//ChTfRHUwkcZlE6D1U6iMj4OMUBqVnJRXc0i80=,tag:ZNFLqIR/VnaayJXopoHQ5w==,type:str]
type: ENC[AES256_GCM,data:UThfXt/8,iv:P0hF0JdBjIBXlGGHjDTbizKjix93RpCe5ZH6YVHYssc=,tag:YUov2S7rLJ9pbOR+KhHnYA==,type:str]
stringData:
    password: ENC[AES256_GCM,data:C6c1iC0dtWZIEn6zApkwQV/pPg==,iv:OXndtwfjaIPoJG775gJEG5lfZ/LPAlTD/6178s94Ul0=,tag:lgD1Hv9fRDXfi9xc3NkIDQ==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWTlKcWZZc213YjVMcU5M
            S1dvRFVWS0Npd0dhanJxQUljVDVaaVYyWWpJCkpiVmlLY0NVVWJoOFI3cVd3bXhV
            emdzYVM2S3cwSi9HU3lYZU1xSkIvWDgKLS0tIHRtZVh1Qmhjc2NpenR4LyttZGpj
            T2FGUlQ3MlhidFhrQlpyOE1FbWJGbzAK3pljsyfvE5/VSL8kxg7ZWptkAPyZP2YM
            3eT+5YkxKJeqAbkyh/iJ2nMScTNm65GFtGmN2uH9g6afdDpuzfmjxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T22:34:29Z"
    mac: ENC[AES256_GCM,data:dDjTxFOLUDhZ+QnkUdIHPjm++4P9Jp3aT7gUiJPZUMx7JD2bB2H9RUL60+erheo/kcEcmL9vJUpHQ7rREcF7Zy5ja7hyO542a3jaOBCABrgeQzuZIO5F1b9llifRVUIU3mgHGDr7sGDd1zG4DjuG84tK/lnGDR5qsAfnVEuj2aA=,iv:ajkK0FOmOcB4J3gs0mF1a1riX1bUbFlE63jMiLvyLIA=,tag:h7gcdv6OEiOC/ai112ym/A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
