apiVersion: ENC[AES256_GCM,data:ke0=,iv:UVJcHIY48PY4gGtI9I3TC0Ogwkom+EEOKDtR/h/WEkc=,tag:lkWzGL3xZQxvZHoqN5nngQ==,type:str]
kind: ENC[AES256_GCM,data:JGgANlaj,iv:vL+auFBP5jweBoansxRNwS9+RAaAcmp+aG6O3llsyVA=,tag:5CFncd5n7zlUFzvNy2Eu7A==,type:str]
metadata:
    name: ENC[AES256_GCM,data:/x9ZsHZAY6mVZCqgexpwfK1NAL5qm3Hy,iv:CbbxVG3LUpGksCfOACZmbCal8IheH4gfsPGjeHjgw4g=,tag:WJ3dmdUQoutogi8Duf2GSA==,type:str]
    namespace: ENC[AES256_GCM,data:9oh97MQn,iv:11Ka2EfVft0m2kyvGApVbBS2vGCx5NXTrDZXXbreQjw=,tag:vOvyW/FBXTVuYTBR5lXmOg==,type:str]
type: ENC[AES256_GCM,data:Yhgk5qwe,iv:3hHFDFTKeHw+A9sQUmOZknmXZW7ksLhev8cJJMXeklc=,tag:1fbcx5MNPN9jXJFfNN7zUg==,type:str]
stringData:
    MEALIE_API_TOKEN: ENC[AES256_GCM,data:eS03Qpc2ZkGc4XeUzhGyd3C72SnGnvdPz04ltsR43Fo07+oqm1cVfnxZ7BWTD9mkglsgvNQMl34/sPp+I84KSqbWmCKgMbzoiagLS+aUD/KRUZrYpM+sWAlXLiC7CESV+QqKuKY9Q2vcDHkfMYwdbKKYr5P+GtVDgc1DVbofA4dTouBeuxOD7jvscumct8SqJIT/lAqjzGoUq6KCMjYMTPDkN7RWpJX/1sj4KAP1VUgxPHNyPBSrTkJ/MpAshDsad8wNqYT7AhCoFKZtk+tjhiZU/Gu5PswHSGBwwyKDWGbdR6HDSBJmvVTPBWq9un0+3BhzbRzurVw5tVxkSU/Zuft15zI=,iv:Tx0DaYcQDh+dIQnHYtC3HIJk3/OnHkz+yb5fu9iwi6A=,tag:uPby6RsH3iLN+emRFWQ2gw==,type:str]
    GOOGLE_MASTER_TOKEN: ENC[AES256_GCM,data:7aVaOtpCA6zZU8es/x/RsHk0vUH561ZTDOQ6RD29nN3a9LaXL1a6CJDILKgRC+znQFpmbaN0UZKQhYVKc5APKmnAWEjpBQ0g24GFvRIlD8F3WW445V9+Y3IqczpsZL4vTu3vbS/eWFmMDbUT/Ur8R0CBR29F46F2RlkLvNzVE9qrpLRlqK5WmJFxFhSBeG4BzvgqBcY/NPItFRg7byVoS7Io28U2fEQweuVsH8G0zjfDYxfNhzytNODH8g0j5PsK/4kEw/SOU7AZiKbt0wKWxQAWiGP9cHAkh7vplysrRA==,iv:NsEoTmV9oL+0x3SF4pH6Ad46bz4TYW01Ecn0CqClySM=,tag:RnuK874dBzH8ZpqOmFAQmw==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSEd6VmxhQ3lUZDVGYWE1
            cUlEZ211YlQzazhzUlpqbzdXaWpVd0JYNm1vCnp3SjhQeUxMR2RWT3RTdjhWUmxR
            QjUxUExXMnpwcTF2NGh3MCtFQXAvR3MKLS0tIHh2QWJFd0NoS21FR0dxdzVOUEh2
            b3ZGWlAxMjNhZ3dKTk9jdzNENmpBL00KS8u3lBXwT09s7zOs/3ERMhx4faTCEcma
            RNlxPzImRL0bBNfAoGriZthkjiErIzQPrFd4FyFGB9rrTxTxC0qNlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-22T14:26:18Z"
    mac: ENC[AES256_GCM,data:s2zPOb5++B/LoGi8uYApqzrliYbQklWzZ1+FPs7WXdE4ET0nA/Ig8aaDJbkv/RXmz6fHCNZG8AMBjlgTNgbVF2XG5pCK4BoHyFLEEiG/aUJJQbTlmACLMuRPbt4lxVNJ1bhiOtkg8zLi2CWVzcJODs1x1S9tfLMh5fzFi7qtdAw=,iv:4Mg/N45PZRQlH4YO79XxzQGXRzIkDQdG2UAxkoN+Hnc=,tag:fGR+l3CetQCZmmMC6SQ0ig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
