apiVersion: ENC[AES256_GCM,data:6II=,iv:iUH/BHzUFuBCDHOEZhcNmFWkgY5t3z2+5iJTJ1sdjUQ=,tag:/RjKYCYdmcWCiSPLjcgn4Q==,type:str]
kind: ENC[AES256_GCM,data:Flp+qAmn,iv:Evu4Bfb4p1y7/yYqa7Bik8gx4bOsGlWfwM3dQmjorlE=,tag:Pj2g0bUhVQcWGVWLhG78Nw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:H+KDHXwxq+uKq1gzO1UJYy/Ddow=,iv:tgPGqd4Xguobb+/Uv3O3f4I3DgYNGUeChyctvSD+ZvU=,tag:UWrCcrdTvtpewECAQd704w==,type:str]
    namespace: ENC[AES256_GCM,data:Mt9DzyvL,iv:CKK5jXYcx2ew0kDBz8bR8LElsrFPO862tdZ7CsyvAxo=,tag:512g8YlUVMPDy6nhpyihGg==,type:str]
type: ENC[AES256_GCM,data:9420wf6D,iv:lnwyJ232tJq5Xrj2AuB2i9qDywFZ/5HJEKnGv4wCtMQ=,tag:HLDHmOFm0xuf0RzTbEYmFg==,type:str]
stringData:
    accessKey: ENC[AES256_GCM,data:RRCkX/+MtMhoJcMOpS19kcDMazQ=,iv:gNwSX7Zug1djOE/wTy2ktvKI3bzB/HgRml7bCebh68Q=,tag:a63jgywJeGCm0pbG/5UurA==,type:str]
    secretKey: ENC[AES256_GCM,data:r5OvkLjHfheZZ8voW1RcQ98LfY73VZLVORbUbJg/XQtjlmIO9IKCJA==,iv:fs72euJ5KQUlfmVVVZUMZvqjB9M+/JQYqSWT2Rsm7e0=,tag:Bxx7E6SBQLEvcWZv51aBvA==,type:str]
    encrKey: ENC[AES256_GCM,data:hL92P26R5lz0ZjVekpcE6wnAAjAD7Bvae1B05jcyG3I7eYWr1Hj/xiHk5XE=,iv:4o616T2SBYojBhNgAO1lIXTjtjTzpk5c1iXSpPy/Pl8=,tag:9N+03chDoC+DtrR8K9zIMg==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYURqZ0JnWDFkZnNHOUZB
            eDYyajRwQWhqRGhQNkNONlRlNUg4cGZlOXdBCjR1U3FaODhsMWlLVi93SUw1NXlR
            ZldvSjNEVDlEVGIydC9WNHVtUzBqYWcKLS0tIDVNM3A1Q1NESzVyVGhBMmV0YTd2
            N1NTcjFKelJ3dWViUkxKN3NQRDVtTzAKH73suTuT4Ld9yvrjZugYRmpuOBjOVjwF
            BLxeI1lnnT5xpP2AsDhER2WNcZWG2ebRlQkgZJpbZwtCROA4sjY3xQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-26T21:47:25Z"
    mac: ENC[AES256_GCM,data:9PTpWhoko8r2Kqr+fQBB68o3+2JSskGM0I+XgQfkDTxUiNrXOMXHIZvAyWlNSmgUp6oSAFAkTYdL4w2V8ockZRIv2mGLPkPnuLSVAxQDRasxnDJv56mufBEy+KEACGzrorWrBktErwsu2D6OwiNPJ5mGWDVajjUbzOuC/cty13k=,iv:vGd/gPdrWAaAMz+DjqxIpcAXA0fpxT5qwLDxMxaZEW0=,tag:n5GuN0wGyLNsrJDONfWfXQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
