apiVersion: ENC[AES256_GCM,data:T24=,iv:eEKEiuHhiSIdMI/wjD4d/frzQtss1HBb93vH9JmJQVU=,tag:x5Ebimz8a3gdvJwuql+AGw==,type:str]
kind: ENC[AES256_GCM,data:kSj+eSct,iv:U6yRUS+8IumXy/C9qesO5jL6/Ioqt+FwPXVOSfVB0bc=,tag:+x7O2Nq5b9GElCpmLHouAw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:nAzRx8ZWKiJoMA4oB4K2dVMW,iv:7SGO+zi4bZwpWqmHDLPQLXrU1Ic2RjBAgdZ/ZDCjbbI=,tag:l7MirwVVHGD/EVWt2Wd6Kw==,type:str]
    namespace: ENC[AES256_GCM,data:MJHyta+v,iv:PeJRtKYDx4STLKLW0h8cP6GY7pgBgjm5pDmu3Zf+woE=,tag:KAfuugT1PhFWN9iBJu4sGQ==,type:str]
type: ENC[AES256_GCM,data:CPn/APuU,iv:3Ajapsq2Dg/tlwiqejXmf7aWmXkbL8K3Xf9dMsSeQ5g=,tag:u+I2jAP2/vR8Sp56LyRCCw==,type:str]
stringData:
    clientSecret: ENC[AES256_GCM,data:6Um3+gsn0+6A8T5vq/nR7FtU6FdK3+8jl1rjuRqlSmOulXB4Qzx9uqwmgk7nJgC0,iv:4hlDj9DLzSFlNdzhIU2Gt6c04L0rH8VKbfyRg6dfTCk=,tag:qQpEghCvqdF4ZznllMI1+Q==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRHR5WFNYaGROb1ZqMnZT
            UTcxU0V6STVCcGxiQ1ZEdmdIaHlZVWU3Mkg0CnpOU2c4Zm1MdU1qSklYdmJPMEYy
            TitWaUdQL1RqYWFKTng3bi8zQXZCRG8KLS0tICsrYUNCd0I0T2FEOGlFYk9sa3hQ
            aUtsWEs4djhYcXlwdGQzZXFiZjQrYWMKlxOHNpQ7+an1sGeMF839ffcrNdJk3cPY
            /26CR85X30ZqQBDCqJz/xiWXo0nY5ta+CebwaZpkvdGoZPxCPUHENg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-18T22:28:10Z"
    mac: ENC[AES256_GCM,data:Yeend3ijsceb8s1E1mKKG+V4Aj50InEYwxrySvo2jaS+qIMNToBxb6AYEhK0mtIuLCcvBBfhRr/w2h6GVRG5DvhR7I9DVGs1LtCyH7qCUzxSbT9Qo+HCux2OcJJlWO1LrYBwbPlytyYGbqs+jowHu2id5mjLMZspGiQHB/nvE9s=,iv:BsIERhWUA7giHG4oS3FQNdNhd/MSTUGlFuckyjcUch8=,tag:Q9WNBLuWXNtVK6RDdUmHvg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
