apiVersion: ENC[AES256_GCM,data:9oQ=,iv:yfZf3POPf0OAWpFBc6pp4K4g5ec4uY621MRSdtjk/So=,tag:/GbCcqJLITo90yMuQ8FRFg==,type:str]
kind: ENC[AES256_GCM,data:KYdvPSsN,iv:wZRPoGeg2DDKrkVJacLFV6l1MWkJVE71jMK0CbI0IbQ=,tag:SVXfm3p59NtXD8qB4BnjGA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:tnj/dWC0QVOsljgVaQLz4yEfPorptGQ=,iv:4TNvEUWiiKVFqC9KYoMT6I16ifOw+Z67B1VRFxepGB8=,tag:jVyOV7J9OyPFIOTnwBoIXA==,type:str]
    namespace: ENC[AES256_GCM,data:2Js25Xse,iv:HsKtKCy/L2NnZV21t6OQlUVLEsnXCjRizx6LDGDF2J8=,tag:6VlWNaFlodEQMWkWBqLWEw==,type:str]
type: ENC[AES256_GCM,data:LNbm2zHA,iv:iZc6knT1icGzhOtoE6rPlfx/h5xE/n2OqgpYW6CHeJM=,tag:AtxxQnNHyAUs4P7ryJEl2w==,type:str]
stringData:
    #ENC[AES256_GCM,data:FpoILN3/4AY/46GUsvscvxK+qGHULy09CqWov330G9oR8aESE5rBAG8nzUB6DSBV7EFzxnQpIbMyJQY16k5dikv82q8+XisPIhPgVg==,iv:tOzOdlPVe8/RY5sjF8z11lHyleS/3jNc+bzvAyOICl0=,tag:ht14n/5fCftmUxkunhxE2w==,type:comment]
    MEALIE_API_TOKEN: ENC[AES256_GCM,data:rSYWaOT4WHmldzM02lHY4Ky1j0FTRylUJDdSvHWPqtdxUr7fV42pRnWVnhFCITAXkVk7YFerX3RMxNEOIeQZ/fRa87sOgXS2DA8Bj5KW2i0qdo8o9w2mcYsySqf6lFOn1Ko0fCKagBbKt+szh5rMl1NvtcGrhLCLwN/y64ZTmsrHrHD9Jsx//gW4xDfzhbdMZX7t+hm0PuTvX7mqJOU84KqHUD51WCFMrhpqM+V0+tRxsPykc//9MyPnYLLj5NPKULYmbUUk0pif2LUuQZqajyL+Rd/QLaPOR+hiqbBWTR3Txu9GFVP2misU5oUbOzQvNOj1nQDueJIlJK7TQLKElfkVinaea485/fITLrCoOw==,iv:Uu9HY3BhhmzPrwwG81Th+g7UHoGhSx0XaviPoShEu9E=,tag:bi3vSPhpheSL7HAwNbZvYQ==,type:str]
    #ENC[AES256_GCM,data:q347ziuku0f0ttgNx9uUTOQAbBMGvGxpZPp8zntPcwEuAEZ8OY9PT4c/I189RsTbU0mCCckojQpz6xQrzk+n35B7XnBv4Q==,iv:KD634lhD5q0DBJ/BYt7lN9S59IdsRYAvEC1EQyFVdg4=,tag:fWqRPsHZ1DSxDs3zKJK+/g==,type:comment]
    PROVIDER_API_KEY: ENC[AES256_GCM,data:4ps2J8YY7ZLXjWmKkgWBYnatkm3qwo+f0EEzmXqjUaC9+PKiEdFpT2Q=,iv:HxPf5wpnDx90OV//DZcTRfJkYJyQogF6LCK+s410Whk=,tag:1RbI1Eax7XJJ/M6t3liKyQ==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3K1Q3ODZJK2VwU2NZaEQ5
            aGZnWWNmNG5EWDdScHIvM0hyTmxwSWc2akNNCms1SXpsRzQ4MUZmUFVkVzV4c0Jr
            T1FSaDk2djVNb3pKSktHZG5jamQ5YUUKLS0tIEczbnBZbkZOZUJnNFgyWWZ2cXRN
            Q1JLZFZCNmx3VWhaQnlYNWdNN09QdkkKHIHVxYG4FcaooFlHWCn04f+1U6ia7oTW
            pjU9VdgEuMf/GJllrvaoTb9KZbba2hiZiOr8tqWbCCMe1bkdpQOtOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-15T21:07:28Z"
    mac: ENC[AES256_GCM,data:ySzPBvUU3fMt/CiLtgDv8jhykvWqVqwgP7/+0v4aIMHab8JsCPhwvm6yqgezH65V4G8U5esNdBeuvDJblbXXW9+3+MphIRxeI2tKpnGYn0Zqtp+mhM4KSkqwU8AsKXDeEhfgb0jMZqbMFPKJbgA6NBNvC/qiFOT7phyIIDGVf6Q=,iv:aKG8SFvSTTYYCWZTUeJp7J2XcNIB0vmgEppinOQ+nlQ=,tag:iPQf2dJy8Qff0IJa54FZjg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
