apiVersion: ENC[AES256_GCM,data:pNs=,iv:Afqvx5ryTsEURPq/oRF1Qo91HuGSfBOraEFj80mPsaM=,tag:6t/OyrY6z6IZmspQURB80g==,type:str]
kind: ENC[AES256_GCM,data:TtrYG4I3,iv:ILcPBIc4hD3Tu4qwBT95oBGfZlaLW5ElRskDe2W2dQY=,tag:7fSk0+siWQHI2FgQ3Ag90g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:kyh3IOfIeq47eJyW/QwWxjjsAHw=,iv:XyhVWmrQcpPBJsDIVnzxTSSrgV2HLBn0pzCzeMHBzpU=,tag:Wtgx3SIKoAgHtRvN/6AyOA==,type:str]
    namespace: ENC[AES256_GCM,data:nXPWlpdokg==,iv:HiPLFloyMcbtHMUrwBkTIqqft5ulxZ63tJ0ssYTu/5E=,tag:k09Ywse0pJeqWI94lPno9Q==,type:str]
type: ENC[AES256_GCM,data:i63kNkjM,iv:O2QeG692KpsRQZaC8U6WRLSchUIauuqmg+TQLHMVJOU=,tag:pcPNWOmkATEIS7mGPlytKA==,type:str]
stringData:
    adminUid: ENC[AES256_GCM,data:hAsZuPoiiLHEwzWDbl6YQA==,iv:+qf6D17qXBN3nTIvhfuD764wsee5rSvIuXZw4doWdSI=,tag:6fatOdBjEcGVAUrRtB1cFw==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBreFpBSzQ5bG9aLy80eEpt
            djg0UWliRWkwZzA2Z2hWMHNhN1F6cVRNRXpJCjFmRENkV0lNczdLV2l1OU1WNlpI
            UDRTUkVJY0p6cU8vVktuSXIrZHowcUkKLS0tIElRVVpPQ1ArRlU5QlNUVms1eU5r
            SHNyU2NqaEV2Nm9DQVVXdFJZRE1td0EKTUjk8MUWLhfvQnAn8/bbhtpwjRC20UF7
            dDlt0QU18hd/PfdQZ4SQUm2qWuQ7VG1EU1PLpsDTWAJnOVVWCIVwPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-30T23:27:15Z"
    mac: ENC[AES256_GCM,data:IU9kPWk6+UsdBhGz4qsZh8pAEVpKmsc4QgcpJ0fkY+H0xwgjHKGxiOfNhg3jTF8KPdeIYmNxK0VtTlwDN3X5kXW89aGL4vsPv1Y/ea/wtA6qZjpMW6SQ95x4e2ZHaYL9JCE2oLC2Zd1g8UABNwARKIq/347zA3Pd6FZPasmYJWw=,iv:qzwGWTEtwgxSlj2pgd95B5gCVZPGxcNXP0fFgE0jtjA=,tag:HP0dIG7aESLluA/FKmQo0Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
