apiVersion: ENC[AES256_GCM,data:rVo=,iv:y1wpYpaA0xerU9hoIQl+VleWkq/WYPzVPspyhTqj1BQ=,tag:a5Rw1c6Vqt7VdEffOBAHJg==,type:str]
kind: ENC[AES256_GCM,data:8lq0V8bU,iv:ZaKWFAfvZQEETrZT89WH4V7tOQRCDmxBAafqaPy3UtM=,tag:AkOFtZBg1wL0i9lAXi1gpQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:19eoZKXB/koJsVXoqAs=,iv:6SSRa58MZaQBXTMvZGPiR8oSmVPn2OGlKT+r1cpYVLY=,tag:dQPxxCjC3jKUr9fPP5pWlg==,type:str]
    namespace: ENC[AES256_GCM,data:99lJPXdAEXeL0A==,iv:LbcHY7MKs5mRJuvA1H9KVo8Oggykz+IqXpans/bu9DY=,tag:Ql8Ol5gJqTFLZMAwUQ4Wcg==,type:str]
type: ENC[AES256_GCM,data:lWzS+khg,iv:d3ln6F26SAP8BCu0GLV+orxU1tu8y0Z0gQnSZo08Zvs=,tag:SU7nR4Dv6iAYxKE7LBYmZw==,type:str]
stringData:
    username: ENC[AES256_GCM,data:TjfFX6eUYJbTgbrOog==,iv:kwIXogG85dOrHX7n5Ulo2lOP6Pcy+1FhQz59jBHT0+0=,tag:8qP30IsInvMlEtBXAXNifg==,type:str]
    password: ENC[AES256_GCM,data:blh5FtxNdQQX/K/HMO1miacpfhdPvWtbjRtBZxLGwRYOk70H3JDi/jKx/BMA+Je6VF5ew2mlQ1Mo0BGu,iv:T9DaKgM4JgiX+whZzQygcCkekDnciDeYYceXTFO9ojY=,tag:2iKKtja13E7psO/kmkteYw==,type:str]
sops:
    age:
        - recipient: age1ldjvn6pafm39l2t6vzk9tnm6lsqcdmxr5wsqnw4vd4cgp5e7hajsgf8hy5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6TVN0NnROY3dRcXkyZGVo
            T1pEdEZKa2NJNVRPeVJyNXNmWHRldklXL2hZCmRFNHlnTExYTkNXVGdNK1ZqbVZs
            NWMxeHJCQkpGU0pYQmdxbkxlR2dvVEkKLS0tIHBrQmEzTWl4NjF5Mnp1MFNPY3c0
            RE1QaWRVTXFucjlyRE1ndFplWDVxSk0KGVij3MdygEdm51kJbkm0GO3d1G0sgXMP
            MP0FLgwaafC1WShj/onHOB/ImrYHuosp5lUc9sZRhAO1eVxL/DFwKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-14T01:48:38Z"
    mac: ENC[AES256_GCM,data:OZVaoNUc7iEb5G70QDrlzcXVcDNJTUG06TTwHksv+0tMfz8d8VSAdBJc76+w1Rb/6cZTRRN3bUjilKdXQFIM71pb/bGJcQVUgW2UsfFae+OXS4/AT/Ai750v7KZwcknBdVwV4HQ25IvIE7V18/M/KTzSweXA9PC8Fn1qex1d8ZQ=,iv:RAkKYXmHbKXhmeXzFOch6h/iHrfddJx9g6G8KiZJrrE=,tag:ucgI2tbQ4LJzztCDlpGycQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
